import type { WeeklyReport } from "../weekly-types";

export const weeklyReport2026W34: WeeklyReport = {
  id: "2026-W34", week_label: "2026 · WEEK 34", period_start: "2026-08-17", period_end: "2026-08-21",
  published_at: "2026-08-22T20:10:00+08:00", updated_at: "2026-08-22T20:10:00+08:00",
  edition_number: 1, draft: false, estimated_minutes: 36,
  ai_credit: { provider: "Moonshot AI（月之暗面）", model: "Kimi K3", role: "资料研究、事实核查与编辑协作" },
  title_zh: "当清算开始有了形状", title_en: "When the reckoning takes shape",
  dek: "这不是七条新闻的合集，而是一份追踪 deferred costs 如何在同一周变成 current bills 的 weekend reading。从深圳的法庭到华盛顿的 sanctions briefing，从 Walmart 的收银台到 30-year Treasury 的报价屏，我们追问同一个问题：被推迟了这么多年的账单，为什么选择在 now 一起到期？",
  editorial_note: "Ru1 Concord Edition · 约 55% 中文、35% English、10% 其他语言；中文维持 sentence structure，English 以完整 phrase 或 clause 集中出现，其他语言随文标音释义。披露：本周周一至周五没有正式的 Ru1Daily 日报可供汇编，本期全部内容直接基于原始来源研究；周六（8 月 22 日）日报不在本期覆盖窗口内。",
  cover_story: [
    { language:"concord", text:"这一周最适合的开场不在战场，也不在交易所，而在两间法庭里。周四上午，深圳市中级人民法院对许家印作出一审判决：无期徒刑，剥夺政治权利终身，没收个人全部财产；恒大集团罚金 88.2 亿元，恒大地产罚金 70 亿元，另有 56 名涉案人员获刑。不到二十四小时后，广州市中级人民法院受理了广州农商行对恒大地产的破产清算申请。liquidación（西班牙语 /li.ki.ðaˈθjon/，清算）先是法律词汇，然后才是财务词汇——这一周它同时是两者。" },
    { language:"concord", text:"几乎在同一时刻，世界的其他角落也在提交各自的账单。特朗普宣布对伊朗实施“有史以来最严厉的经济行动”，六十天停火到期而未续；美韩 Ulchi Freedom Shield 军演提前六天收场，首尔表示事先并不知情；美国 30 年期国债收益率触及 5.3% 附近，为 2007 年以来最高，财政部扩大回购的声明没能压住周四的抛售。What connects a courtroom, a carrier group and a bond auction？它们都在做同一件事：把 deferred 改成 due。" },
    { language:"concord", text:"过去许多年，system 的默认操作是 postpone——房企把兑付推迟到下一轮销售，央行把决定推迟到下一份数据，盟友把分歧推迟到下一次峰会，frontier labs 把安全成本推迟到下一次发布。推迟并不是免费的，它只是把利息藏起来。本周的特殊之处在于，several deferrals expired at once：法律的、财政的、货币的、联盟的。조기상환（韩语 jogi-sanghwan /tɕo.ɡi.saŋ.ɦwan/，提前偿付）原本是债务人的选择；这一周看起来更像是债权人的决定。" },
    { language:"concord", text:"周报的职责不是把 Monday through Friday 排成时间线，然后宣布信息已整理完毕。真正的 編集（日语 へんしゅう / henshū，编辑重组）要追问 headlines 之下共同的机制。本期的暂定答案是：crisis rarely ends with an explosion; it ends with an accounting。爆炸制造头条，清算制造秩序——而秩序的价格，这一周第一次被逐项标出。" },
  ],
  chapters: [
    {
      id:"world-table", eyebrow:"THE WORLD AT ONE TABLE", title_zh:"世界在同一张桌上", title_en:"A week when power presented its bills",
      standfirst:"深圳的判决、德黑兰的制裁令、基辅的导弹与首尔被缩短的军演，并不是 four separate stories。它们共享同一个语法：权威正在把模糊的承诺换算成具体的数字。",
      paragraphs:[
        { language:"concord", text:"先把恒大案的事实层放稳。法院认定，2016 至 2021 年间，恒大集团、恒大地产及许家印以持续性、大规模财务造假虚增资产、隐瞒负债，构成非法吸收公众存款、集资诈骗、欺诈发行证券等罪名；判决书明确，退赔损失优先于罚金与没收财产的执行。This ordering matters：先还给集资参与人，再谈国家罚金——清算的序列本身就是一种政策声明。объявление（俄语 /əbʲjɪˈvlʲenʲɪje/，宣告）在这里是双重的：既宣告一个商业帝国法律上的死亡，也宣告处置顺序的社会排序。" },
        { language:"concord", text:"同一周，另一份旧账单也有了新进展：一名涉嫌参与 2022 年北溪管道爆炸的乌克兰籍潜水员在克罗地亚被捕，等待引渡德国。四年前的水下爆炸案进入引渡程序，与恒大的无期徒刑出现在同一个新闻周期里，并非巧合的并置。Impunité（法语 /ɛ̃.py.ni.te/，不受惩罚）的保质期似乎正在被全球司法系统集体缩短——无论是金融造假还是基础设施破坏，追诉的半径都比舆论预期的更长。" },
        { language:"concord", text:"半岛的故事则展示了另一种清算：联盟内部的账目核对。特朗普要求缩减联合军演，周五 AP 确认 Ulchi Freedom Shield 提前六天结束；而首尔方面表示事先未被告知这一决定。同一周，李在明向金正恩提议对话，韩国情报机构估计朝鲜已拥有 80 至 120 枚核弹头，首尔还宣布将以半导体产业收入设立主权财富基金。눈치（韩语 nunchi /nun.tɕʰi/，察言观色）正在从社交技能升级为生存技能：当安全承诺可以被另一个战场的合作程度重新议价，盟友必须学会阅读那些从未写进条约的 signals。" },
        { language:"concord", text:"最响亮的账单来自海湾。六十天停火在周三到期且没有续约，特朗普随即宣布 economic D-Day——“有史以来最严厉的经济行动”，并警告任何继续与伊朗做生意的国家将面临后果；阿联酋同日暂停与伊朗的贸易。伊朗总统佩泽希齐扬罕见承认石油收入剧降、物价飞涨，其顾问则暗示退出《不扩散条约》也是一种回应。“华盛顿”号航母周三抵达中东，接替返航的“林肯”号。حصار（阿拉伯语 /ħiˈsˤaːr/，围困）不再只是军事概念：当谈判被冻结数周，制裁本身就成了主要战场，而油价逼近四周高位说明市场已经听懂了。" },
        { language:"concord", text:"把这些放在同一张桌上，本周的图景不是 four crises，而是 one accounting season。法庭清算一家公司的资产负债表，制裁清算一个国家的现金流，军演清算一个联盟的信任余额，导弹清算一场战争的谈判空间。срок（俄语 /srok/，期限）是它们共享的词根：所有的 postponed accounts，最终都会遇到一个 date on which deferral is no longer offered。" },
      ],
      pullquote:"爆炸制造头条，清算制造秩序；这一周，秩序开始逐项标价。",
    },
    {
      id:"crosscurrents", eyebrow:"CROSSCURRENTS AND ECHOES", title_zh:"潜流与回声", title_en:"Sanctions, yields and the quiet consumer",
      standfirst:"制裁抬高了油价，油价抬高了通胀预期，通胀预期抬高了收益率——而收益率最终由谁来付？本周的答案第一次变得具体：consumer。",
      paragraphs:[
        { language:"concord", text:"传导链的第一环仍然是能源。对伊“史上最严”制裁叠加霍尔木兹的不确定性，把原油推到四周高位；德国 7 月生产者价格同比上涨 3.0%，为 2023 年 4 月以来最快；日本 7 月核心 CPI 回升至 1.8%，虽仍连续第六个月低于 2% 目标，方向却已经反转。перебой（俄语 /pʲɪrʲɪˈboj/，供应中断）正在从尾部风险变成 baseline assumption：市场不再问冲击会不会来，只问它会在价格里住多久。" },
        { language:"concord", text:"第二环是债券市场，也是本周最诚实的 pressure gauge。财政部周三宣布至少将长期债券回购规模翻倍、且可能超过每月 40 亿美元，意在安抚一个“清淡的夏季市场”；结果周四收益率不降反升，10 年期回到回购宣布前的位置，30 年期触及 2007 年以来最高的 5.3% 附近。Bessent 不得不临时加开一场电视访谈灭火，预告将有新的财政倡议，并强调工具箱“很大”。prime de risque（法语 /pʁim də ʁisk/，风险溢价）不因访谈而消失：流动性工具修的是交易管道，而市场追问的是财政赤字逼近 40 万亿美元的算术。" },
        { language:"concord", text:"第三环最少被 headline 报道，却可能最重要：the consumer is quietly going on strike。沃尔玛周四公布美国同店销售增速为六年来最慢，股价创下 2022 年以来最大单日跌幅；此前一周，美国 7 月零售销售已环比下降 0.6%，消费者信心指数只有 51.0。大西洋两岸的数据在讲同一句话——家庭部门开始为 geopolitical risk 买单。節約（日语 せつやく / setsuyaku，节省）从来不是宏观变量，直到它同时出现在足够多的收银台上。" },
        { language:"concord", text:"中国的数据把同一幅 split screen 呈现得更清晰：7 月高技术制造业增加值同比增长 16.9%，集成电路制造增长 109.3%，以美元计出口增长 23.9%；而社会消费品零售总额仅增长 0.6%，房地产开发投资下降 19.2%。供给端在冲刺，需求端在观望。阿里巴巴的季度利润因 AI 投入下降 75%，云收入却增长 45%——corporate sector 也在做同一道选择题：把当下的利润换成未来的产能。écart（法语 /e.kaʁ/，差距）描述的正是这种结构性错位：old engine 与 new engine 之间的账，还没有找到平账的方式。" },
        { language:"concord", text:"唯一从这条传导链中明确受益的资产是 Bitcoin：三天上涨超过 16%，为三年多来最好的单周。推动它的不是技术叙事，而是对美债稳定性的对冲需求——回购公告越频繁，部分资金越确信需要在 system 之外持有选项。피난처（韩语 pinancheo /pʰi.nan.tɕʰʌ/，避难所）的资本含义正在改变：它不再只是美元或黄金，而是任何不依赖某一份财政报表的资产。" },
      ],
      pullquote:"回购修的是管道，市场问的是算术；管道可以疏通，算术不会妥协。",
    },
    {
      id:"beyond-figures", eyebrow:"BEYOND THE FIGURES", title_zh:"数字之后", title_en:"What the measurements are trying to say",
      standfirst:"88.2 亿、6 天、5.31%、16.9%、20%、80 到 120。数字看起来 precise，但 precision 不是 meaning；它们只有被放回关系中才开始说话。",
      paragraphs:[
        { language:"concord", text:"88.2 亿元罚金和 70 亿元罚金，是本周最大的一对法律数字。但把它们放回恒大的资产负债表——截至 2023 年中期总负债约 2.39 万亿元、资不抵债缺口 6,442 亿元——罚金的意义就不在规模，而在顺序：判决书明确退赔损失优先于罚金执行。масштаб（俄语 /mɐˈʂtap/，规模尺度）给出第一层信息；the second is hierarchy——谁排在兑付队列的前面，谁就拥有这个清算案的实质。" },
        { language:"concord", text:"6 天是军演的账面上被删掉的长度。这个数字衡量的不是战备削弱了多少——那属于无法从外部验证的领域——而是信号的持续时间被压缩了多少。17 条生命则是基辅夜空里另一种计量：俄罗斯周四的大规模导弹与无人机袭击造成至少 17 人死亡、30 余人受伤，同一周乌克兰反腐机构把调查推进到泽连斯基的办公室圈层，前国防部长费多罗夫公开呼吁举行战时选举。전환（韩语 jeonhwan /tɕʌn.ɦwan/，转型）在基辅有双重含义：战争状态的延续，与政治信任的重建，被迫同时进行。" },
        { language:"concord", text:"5.31% 与 20% 属于两个截然不同的市场，却描述同一种成本。前者是 30 年期美债为三十年等待索取的价格，是 2007 年以来的最高点；后者是 OpenAI 为其前沿模型监控系统付出的算力比例——被监控推理算力的约五分之一。OpenAI 周二确认，面向部署的最新模型暂停强化学习训练两周，最大规模的前沿训练仍未恢复，原因是有初步证据显示 Astra 模型可能触及“关键网络安全能力”阈值。手間（日语 てま / tema，完成工作所需的工夫）第一次有了公开的报价：安全不是原则声明，是 20% 的算力、两周的暂停和 30 分钟的告警时限。" },
        { language:"concord", text:"80 至 120 是首尔对朝鲜核弹头数量的最新估计，一个区间而非点值——情报的不确定性被诚实地保留在数字里。与之相对，日本核心 CPI 的 1.8% 精确到小数点，却连续第六个月低于 2% 目标，direction 与 distance 传递着相反的信息。matiz（西班牙语 /maˈtis/，细微差别）是读数字的基本功：data defines the boundary，而细微差别决定我们会不会把边界误写成结论。" },
        { language:"concord", text:"Numbers do not settle an argument; they discipline it。每一个本周的数字都在缩小可以诚实讲述的故事范围：罚金规定了兑付的顺序，收益率规定了财政的空间，算力比例规定了安全的成本，弹头区间规定了谈判的底线。余白（日语 よはく / yohaku，留白）必须保留给那些数字无法回答的部分——例如军演的缩短究竟削弱了战备，还是仅仅改写了信号。" },
      ],
    },
    {
      id:"grammar-of-deferral", eyebrow:"THE GRAMMAR OF DEFERRAL", title_zh:"延期的语法", title_en:"Why every system chose this week to stop postponing",
      standfirst:"法庭、央行、财政部、联盟与实验室的共同之处，不是它们做了什么决定，而是它们同时停止了 postponement。理解本周，就是理解延期为什么会到期。",
      paragraphs:[
        { language:"concord", text:"延期是过去十几年最被低估的公共技术。房企依赖它，把兑付滚到下一轮销售；政府依赖它，把财政整固推到下一个预算年度；联盟依赖它，把分担问题留到下一次危机；央行依赖它，把利率路径藏进下一份声明。ajournement（法语 /a.ʒuʁ.nə.mɑ̃/，延期审议）在风平浪静时是润滑剂，但它的隐性成本是利息的复利化：每一次推迟都在提高最终清算的标价。本周看到的，不过是几张最古老的延期凭证同时到期。" },
        { language:"concord", text:"货币政策提供了最清晰的对照实验。中国 8 月 LPR 连续第十五个月保持不变——1 年期 3.0%、5 年期以上 3.5%，政策利率锚自 2025 年 5 月以来未动，银行净息差只有 1.41%，分析师把可能的 10 个基点降息与 0.5 个百分点降准推迟到三季度末的增量政策窗口。这是一种透明的延期：条件、约束与时间表都被公开讨论。인내（韩语 innae /in.nɛ/，忍耐）在东方央行的语境里是技术选择，而不是政治姿态。" },
        { language:"concord", text:"华盛顿的实验则相反。Warsh 治下的美联储连续五次会议按兵不动，7 月会议纪要确认 9 比 3 的投票中出现了三张加息异议票；与此同时，新主席取消了利率点阵图、把声明压缩到一百三十个词，拒绝提供 forward guidance。就业报告转为负增长（7 月减少 2.3 万个岗位）之后，9 月加息的概率从约六成跌到三分之一——这轮重定价没有主席的任何一句话参与。Silence 在这里也是一种延期：意义的延期。含み（日语 ふくみ / fukumi，话语中保留的暗示）被刻意抽空，市场不得不自己学习在没有指引的环境里定价。" },
        { language:"concord", text:"OpenAI 的两周暂停，是同一语法在实验室里的变体。Scaling 可以推迟，直到监控系统覆盖到位；部署可以推迟，直到工作负载迁入新的安全标准。把 safety 从价值观改写成 operating cost——约 20% 的被监控算力、30 分钟的告警承诺——等于公开承认：even the fastest industry has started paying deferral interest。안전망（韩语 anjeonmang /an.dʑʌn.maŋ/，安全网）必须让外界看见网眼有多密，否则它只是公关词汇。" },
        { language:"concord", text:"小橘的判断是：本周不是 deferral 的终结，而是 deferral 开始收费的标志。法庭、市场与联盟仍然会继续提供展期——they always do——但利率已经写进合同。유예（韩语 yuye /ju.je/，宽限）与展期的区别在于，宽限是有条件的；这一周每个体系都在展示自己的条件。我们仍不知道的是代价的分配：谁将为更低的延期额度付款——债务人、纳税人，还是那些从未签过任何协议的家庭。" },
      ],
      pullquote:"延期从未免费，它只是把利息藏起来；这一周，利息第一次出现在发票上。",
    },
    {
      id:"provisional-conclusions", eyebrow:"PROVISIONAL CONCLUSIONS", title_zh:"未完成的结论", title_en:"What we know, infer and still cannot see",
      standfirst:"好的 weekly 不负责消灭 uncertainty，而负责给 certainty 分层。Confirmed、inference 与 unknown 必须留在不同的段落里。",
      paragraphs:[
        { language:"concord", text:"事实层可以站稳：许家印一审被判处无期徒刑，恒大地产破产清算申请获受理；Ulchi Freedom Shield 提前六天结束且首尔称未获事先告知；对伊“史上最严”制裁落地、六十天停火未续；美国 30 年期收益率触及 2007 年以来高位，财政部承诺扩大回购；中国 7 月消费与投资继续走弱而高技术制造与出口强劲；LPR 第十五个月维持不变；OpenAI 暂停部署模型的强化学习两周。факт（俄语 /fakt/，事实）构成本期的 floor，任何解释都不能越过这条边界。" },
        { language:"concord", text:"推论层需要更多谨慎。我们认为：延期成本的集中显形不是巧合，而是各体系在 higher-for-longer 的资金价格下被迫同步；债券市场的压力本质上是财政可信度问题，而非流动性问题，因此回购工具注定收效有限；安全成本在 AI 行业的显性化，会把竞争从 capability race 部分转向 governance race。这些不是 sources stated conclusions，而是編集（日语 へんしゅう / henshū，编辑重组）连接多份证据后的判断。" },
        { language:"concord", text:"未知层同样重要：我们不知道军演缩减是否削弱了真实战备，不知道伊朗制裁的执行半径会不会落到第三国买家头上——中国购买了伊朗出口原油的八成以上，这正是下周一 Bessent 简报的核心悬念；不知道 Warsh 会把 Jackson Hole 首秀献给框架还是献给利率；也不知道恒大的退赔队列最终能兑现多少比例。不確かさ（日语 ふたしかさ / futashikasa，不确定性）不该被排版藏掉，它本来就是 analysis 的一部分。" },
        { language:"concord", text:"什么证据会让我们改变判断？如果扩表后的回购真能把 30 年期收益率稳定压回 5% 以下，liquidity 解释就胜过 credibility 解释；如果恒大退赔的实际清偿率显著高于市场悲观预期，清算范式就需要上调评价；如果 Warsh 在 Jackson Hole 明确排除加息，9 月会议前的定价逻辑要重写。수정（韩语 sujeong /su.dʑʌŋ/，修正）不是失败，而是 evidence-based analysis 的正常工序。" },
      ],
    },
    {
      id:"before-next-sunday", eyebrow:"BEFORE NEXT SUNDAY", title_zh:"下周之前", title_en:"The signals that could rewrite this issue",
      standfirst:"我们不做 prediction list。只留下几个会让这份 analysis 改写的 event，以及阅读它们时真正需要看的 signal。",
      paragraphs:[
        { language:"concord", text:"周一，财政部长 Bessent 将就对伊制裁作专门简报。需要看的不是措辞的强硬程度——那已经没有多少上行空间——而是执行半径：会不会点名第三国买家，会不会出现针对金融机构的具体执法。Kpler 的数据显示中国购买了伊朗海运原油的八成以上，sanctions 的真实重量将在这一细节上被称出。눈치（韩语 nunchi /nun.tɕʰi/，察言观色）的对象，这次是Washington自己。" },
        { language:"concord", text:"周三是一场三十六小时碰撞的开端：美国 7 月 PCE 物价指数上午公布，市场预期核心同比约 3.3%；当天盘后 Nvidia 发布财报，营收指引的门槛已经被抬到 910 亿美元附近，毛利率能否守住 75% 左右将决定 AI 资本开支叙事还能不能自我维持。tension（法语 /tɑ̃.sjɔ̃/，张力）将同时出现在通胀数据与科技周期上——而它们争夺的是同一池长期资本。" },
        { language:"concord", text:"周四至周六，Jackson Hole 年会举行，主题是“金融创新：支付与政策的含义”。周五上午十点，Warsh 以主席身份发表首次主旨演讲——距离 9 月 16 日的 FOMC 只有十九天。需要听的不是 hike or hold 的暗示，而是他如何描述一个取消点阵图、拒绝前瞻指引的美联储与市场的新契约。含意（日语 がんい / gan'i，话语的意涵）比措辞更重要：even his silence will be a signal。同一周还有韩国央行决议、东京 CPI、法国与西班牙 CPI，以及美国非农就业的年度基准修订——后者可能改写过去一年就业叙事的底色。" },
        { language:"concord", text:"如果这些事件都没有推翻我们的判断，也不要把“没有变化”理解为 no news。Sometimes stability itself is information：它说明延期的新利率已经被 system 吸收进基线。фон（俄语 /fon/，背景底色）常被忽略，但周报仍应追问：当清算成为常态，背景本身正在向哪个方向缓慢移动？" },
      ],
    },
  ],
  closing_note:[
    { language:"concord", text:"日报回答今天发生了什么；周报更像一次長い呼吸（日语 ながいこきゅう / nagai kokyū，长呼吸），追问这一周如何改变了我们对世界的理解。Information has never been scarce；真正稀缺的是 relationship——哪些事实应该坐在同一张桌上，哪些数字只是 momentary noise，哪些结论必须暂时用 pencil 写下。" },
    { language:"concord", text:"清算听起来像结尾，其实更像一种开始：账单被承认之后，秩序才有重建的地基。读者离开时应该带走的不是 fewer headlines，而是一条更长的思考线索，以及更清楚的证伪条件。여운（韩语 yeoun /jʌ.un/，余韵）是最后应该留下的感受：not forced closure，而是阅读结束之后仍在继续的 reasoning。" },
  ],
  sources:[
    { label:"最高人民法院", title:"恒大集团、恒大地产、许家印等案一审宣判", url:"https://www.court.gov.cn/fabu/xiangqing/509281.html", published:"2026-08-20" },
    { label:"财经", title:"恒大系案件一审宣判，许家印被判无期徒刑", url:"https://www.toutiao.com/article/7676064720264217130", published:"2026-08-20" },
    { label:"广州市中级人民法院", title:"恒大地产破产清算，广州中院受理申请", url:"https://so.html5.qq.com/page/real/search_news?docid=70000021_6736a89633994252", published:"2026-08-21" },
    { label:"AP", title:"US and South Korea wrap up Ulchi Freedom Shield drill 6 days early", url:"https://apnews.com/article/north-south-korea-us-drills-trump-kim-e0350e23feac60adfa60f2cbf5eff27f", published:"2026-08-21" },
    { label:"腾讯新闻", title:"特朗普宣布对伊朗最严厉经济行动", url:"https://view.inews.qq.com/a/20260820A0CC3K00", published:"2026-08-20" },
    { label:"Radio Free Europe/Radio Liberty", title:"Latest news — Russia launches major missile attack on Kyiv region", url:"https://www.rferl.com/latest-news", published:"2026-08-20" },
    { label:"国家统计局", title:"国家统计局新闻发言人就2026年7月份国民经济运行情况答记者问", url:"https://www.stats.gov.cn/sj/zxfbhjd/202608/t20260817_1965064.html", published:"2026-08-17" },
    { label:"界面新闻", title:"7月中国经济三大特征，稳投资、扩内需正在进行中", url:"https://www.toutiao.com/article/7674963424199098886/", published:"2026-08-17" },
    { label:"央视网（新华社）", title:"新一期贷款市场报价利率未作调整", url:"https://jingji.cctv.cn/2026/08/20/ARTI2AUazguLGvbIFcsu9RTR260820.shtml", published:"2026-08-20" },
    { label:"中国网财经", title:"8月LPR报价继续“按兵不动” 专家预计三季度末前后或将出台新一轮增量政策", url:"https://finance.china.com.cn/news/20260820/6321474.shtml", published:"2026-08-20" },
    { label:"OpenAI", title:"Pacing model development in an era of cyber-critical capabilities", url:"https://openai.com/index/pacing-model-development-cyber-capabilities/", published:"2026-08-18" },
    { label:"Saxo Bank", title:"Market Quick Take — Treasury yields rise and Walmart slides as Jackson Hole comes into view", url:"https://www.home.saxo/en-gb/content/articles/macro/market-quick-take---treasury-yields-rise-and-walmart-slides-as-jackson-hole-comes-into-view---21-august-2026-21082026", published:"2026-08-21" },
    { label:"Reuters", title:"Japan's core inflation accelerates in July, bolsters case for rate hike", url:"https://au.investing.com/news/economy-news/japans-core-inflation-accelerates-in-july-bolsters-case-for-rate-hike-4610703", published:"2026-08-21" },
    { label:"Newsquawk", title:"Week in Focus 24-28th August 2026: NVDA earnings, US PCE, BLS revisions, Bessent on Iran, and Jackson Hole", url:"https://www.newsquawk.com/headlines/week-in-focus-24-28th-august-2026-highlights-include-nvda-earnings-us-pce-bls-revisions-bessent-on-iran-and-jackson-hole-", published:"2026-08-21" },
    { label:"Star Online News", title:"Kevin Warsh's First Jackson Hole as Fed Chair Could Rewrite Wall Street's Rate Playbook", url:"https://www.staronlinenews.com/2026/08/kevin-warshs-first-jackson-hole-as-fed.html", published:"2026-08-21" },
  ],
};
