import type { FinanceReport } from "../finance-types";

export const financeReport20260824: FinanceReport = {
  id: "2026-08-24",
  date: "2026-08-24",
  published_at: "2026-08-24T19:48:25+08:00",
  updated_at: "2026-08-24T19:48:25+08:00",
  edition_number: 3,
  draft: false,
  estimated_minutes: 18,
  ai_credit: { provider: "OpenAI", model: "GPT5.6terra", role: "资料研究、事实核查与编辑协作" },
  market_as_of: "2026-08-24 19:48（北京时间；亚太为当日收盘，美欧为 8 月 21 日最近完整收盘）",
  title_zh: "影子银行：不在银行表内的信用，怎样仍然像银行一样运转",
  title_en: "Shadow banking: when credit behaves like a bank outside the bank",
  dek: "影子银行不是“地下银行”的同义词，而是银行体系之外仍在做信用中介的活动。用中植集团实质合并破产清算案看一条资金链怎样从财富管理产品延伸到长期、难处置的资产；再看今天亚洲市场，科技成长股下跌与黄金、农业板块走强，提醒我们区分流动性、期限与风险承担者。",
  learning: {
    category: "金融机构与稳定",
    category_en: "Financial institutions & stability",
    title_zh: "影子银行：谁在替银行做“借短投长”",
    title_en: "Shadow banking: who performs bank-like credit intermediation",
    standfirst: "“影子银行”现在更常被监管机构称为非银行金融中介（NBFI）。名称变得中性，并不意味着风险消失：只要一个机构或一组产品把短期可赎回的钱投向长期、难出售或高波动的资产，或依靠杠杆放大信用，它就可能产生与银行类似的挤兑和传导风险。关键不在于它有没有银行牌照，而在于期限、流动性、杠杆和风险最终落在谁的资产负债表上。",
    minutes: 9,
    blocks: [
      {
        heading: "它是什么：看功能，不要先看标签",
        text: "传统商业银行吸收存款、发放贷款，并以资本、流动性监管和最后贷款人安排来承受压力。影子银行／NBFI 则覆盖信托、货币市场基金、私募信贷基金、证券融资、部分资产管理产品等更宽的集合。它们多数是合法、也常有经济价值的金融中介；FSB 的窄口径监测并不把所有非银行机构都当作风险来源，而是聚焦那些具有银行式金融稳定脆弱性的活动：期限或流动性转换、杠杆，以及不完全的信用风险转移。换句话说，保险公司或基金“在银行之外”并不自动等于影子银行；要先问它是否在承诺短期退出、持有长期资产，或把同一份风险通过多层合同重新打包。",
      },
      {
        heading: "三台发动机：期限、流动性与杠杆",
        text: "第一台发动机是期限转换：投资者随时或较快到期的资金，支持了多年后才能回收的项目。第二台是流动性转换：产品看上去可以赎回，底层资产却未必能在同一天按合理价格卖掉。第三台是杠杆：用回购、保证金、借款或嵌套结构，让一单位本金控制多单位资产。单独存在时这些安排未必失控；危险发生在市场下跌、赎回增加或追加保证金同时到来时。机构为了筹现金被迫出售资产，价格下跌又触发更多赎回和保证金要求——这就是不必叫作“银行挤兑”的挤兑机制。",
      },
      {
        heading: "为什么仍会传到银行：银行不是旁观者",
        text: "银行与非银行中介常通过授信额度、托管、回购融资、衍生品保证金、理财产品代销和交叉持仓相连。压力首先出现在基金、信托或交易商，并不保证停在那里：一方出售资产会压低抵押品价格，另一方提高折扣或追缴保证金，银行的授信和交易对手敞口随之变化。巴塞尔委员会 2025 年的专题报告把这种“互联性”列为持续监测重点。对读者而言，看到某类产品承诺较高收益时，比起先判断它“是不是银行”，更有用的问题是：资金能否随时退出？底层资产多久能卖？谁提供融资？谁在最坏情况下承担损失？",
      },
      {
        heading: "不是道德判断：它也提供了真实的融资功能",
        text: "把影子银行一概说成“坏银行”会遮住问题。信托、基金和证券化可以把储蓄导向中小企业、基础设施或不能完全依赖银行贷款的领域，也能分散信用风险、丰富投资者选择。政策目标不是把所有非银行信用赶回银行表内，而是让流动性承诺、估值、杠杆、信息披露和风险承担彼此匹配。FSB 因此逐步采用 NBFI 一词：监管要处理的是一组异质的业务模式，而不是一个神秘的单一部门。",
      },
    ],
    case_study: {
      event: "中植集团等 316 家企业实质合并破产清算：产品链条在资产处置时如何被看见",
      period: "2024-01 受理；2026-04 实质合并破产清算获裁定；2026-06 第一次债权人会议",
      text: "这个案例适合用来理解“链条”，不适合把它简化为所有信托或财富管理产品的结论。北京一中院 2024 年受理中植企业集团破产清算；此后，法院于 2026 年 4 月裁定中植集团等 316 家企业实质合并破产清算，并在 6 月召开第一次债权人会议。管理人公告披露，相关企业持有的金融产品类型包括二级市场股票、信托计划、公募基金、私募基金、资管计划和债券收益权。把这些事实放在一起，可以看到典型难题：财富管理端面对的是持有人和兑付安排，资产端面对的却可能是多类型、期限不同、处置难度不同的投资；当现金流不足以覆盖到期义务时，问题从“产品收益”转为清产核资、资产处置、债权申报与法定清偿顺序。它说明影子银行风险的核心不是某个产品名称，而是流动性承诺与可变现资产之间能否持续匹配。法院程序正在进行，实际回收和分配结果不能在本期预判。",
    },
    pros: {
      label: "它能解决什么",
      items: [
        "为银行贷款以外的企业和项目提供融资渠道，扩大融资供给的来源",
        "用基金、信托或证券化把风险与期限配置给不同风险承受能力的资金方",
        "在披露、估值和流动性安排充分时，提升资本市场的配置效率与产品选择",
      ],
    },
    cons: {
      label: "它最容易在哪些地方失衡",
      items: [
        "短期赎回承诺对应长期或低流动性资产，市场压力下可能出现被迫出售",
        "多层嵌套、回购和衍生品保证金会放大杠杆，也让风险归属更难识别",
        "代销、授信、托管和交叉持仓让非银行压力可经由交易对手传回银行与市场",
      ],
    },
    takeaways: [
      "影子银行不是“非法”的同义词；判断风险要看它是否在做银行式信用转换，而不是只看牌照或产品名称",
      "任何高流动性承诺都要对应同样可靠的现金来源；资产能否卖出、何时卖出、按什么价格卖出是核心",
      "中植案例仍在法定清算程序中；它适合说明期限与资产处置的错配，不应用来替代对个别产品的事实判断",
    ],
  },
  markets: [
    {
      id: "cn",
      region_zh: "中国内地",
      region_en: "China Mainland",
      as_of: "2026-08-24 收盘",
      indices: [
        { name: "上证指数", close: 3882.01, change_pct: -0.59, extra: "两市成交约 2.01 万亿元" },
        { name: "深证成指", close: 13794.29, change_pct: -2.13 },
        { name: "创业板指", close: 3431.89, change_pct: -3.21 },
      ],
      commentary: "成长板块调整更深：科创综指跌 3.10%，全市场近 4000 只个股下跌；黄金、煤炭、种业与航运逆势活跃。这里的“放量下跌”是成交与价格的描述，不等于对后市作出方向判断。",
    },
    {
      id: "hk",
      region_zh: "中国香港",
      region_en: "Hong Kong",
      as_of: "2026-08-24 收盘",
      indices: [
        { name: "恒生指数", close: 25517.33, change_pct: -1.89 },
        { name: "国企指数", close: 8471.36, change_pct: -1.89 },
        { name: "恒生科技指数", close: 4594.04, change_pct: -3.61 },
      ],
      commentary: "大型科技与芯片股普遍走弱，恒生科技指数跌幅大于恒指。阿里巴巴配售消息是单一公司融资事件；指数下跌还反映了多只科技股同时承压，不能把全部市场波动归为同一个原因。",
    },
    {
      id: "jp",
      region_zh: "日本",
      region_en: "Japan",
      as_of: "2026-08-24 收盘",
      indices: [
        { name: "日经 225", close: 65528.09, change_pct: -0.74 },
      ],
      commentary: "日经 225 收跌 488.27 点。与韩国市场同日走弱相比，日股跌幅较小；仅凭单日指数不能判定跨市场的共同驱动，需继续观察汇率、利率与半导体供应链消息。",
    },
    {
      id: "kr",
      region_zh: "韩国",
      region_en: "South Korea",
      as_of: "2026-08-24 收盘",
      indices: [
        { name: "KOSPI", close: 6696.96, change_pct: -3.12 },
      ],
      commentary: "KOSPI 当日跌幅超过 3%，明显大于日经 225。韩国指数对大型半导体与出口公司权重较高，因此应把指数表现与成分结构分开阅读，不能直接外推到所有韩国企业。",
    },
    {
      id: "us",
      region_zh: "美国",
      region_en: "United States",
      as_of: "2026-08-21 收盘（美东时间；最近完整交易日）",
      indices: [
        { name: "道琼斯工业指数", close: 53277.01, change_pct: 0.98 },
        { name: "标普 500", close: 7674.37, change_pct: 0.43 },
        { name: "纳斯达克综合指数", close: 26180.45, change_pct: 0.43 },
      ],
      commentary: "周五反弹收盘，但周度表现仍为下跌。由于本期生成时美股尚未完成 8 月 24 日交易，这里不混入盘前或盘中报价。",
    },
    {
      id: "eu",
      region_zh: "欧洲",
      region_en: "Europe",
      as_of: "2026-08-21 收盘（最近完整交易日）",
      indices: [
        { name: "英国富时 100", close: 10816.56, change_pct: 0.64 },
        { name: "德国 DAX", close: 26136.56, change_pct: 0.59 },
        { name: "法国 CAC 40", close: 8484.43, change_pct: 0.37 },
      ],
      commentary: "三大欧洲基准当日均收高。它们与 8 月 24 日亚太市场并非同一交易时点，本期把日期明确分开，避免把不同收盘数据当成同一时刻的横向比较。",
    },
  ],
  movers: [
    {
      id: 1,
      kind: "市场风格",
      kind_en: "Market breadth",
      market: "A股",
      title: "成长板块调整，黄金、种业与煤炭逆势走强",
      text: "上证指数跌 0.59%，深证成指跌 2.13%，创业板指跌 3.21%；A 股成交约 2.01 万亿元。贵金属、煤炭、种业和航运走强，算力硬件与部分医药板块回调。单日的板块强弱反映当日资金与估值的再配置，不能直接等同于企业长期现金流变化。",
      source_label: "央广财经 / 东方财富",
      source_url: "https://finance.eastmoney.com/a/202608243851063569.html",
    },
    {
      id: 2,
      kind: "融资事件",
      kind_en: "Financing",
      market: "港股",
      title: "阿里巴巴配售融资约 800 亿港元，港股跌 8.54%",
      text: "阿里巴巴以每股 112.7 港元配售 7.1 亿股，报道所述融资规模约 800 亿港元；公司表示资金将投向 AI。港股当日跌 8.54%。配售折让、股份供给增加和投资者对资本开支的判断都可能影响价格，不能把单日跌幅解释为单一变量的结果。",
      source_label: "香港商报 / 香港 01",
      source_url: "https://global.hk01.com/%E5%8D%B3%E6%97%B6%E4%B8%AD%E5%9B%BD/60382975/%E9%98%BF%E9%87%8C%E5%B7%B4%E5%B7%B4%E6%B8%AF%E8%82%A1%E5%BC%80%E5%B8%82%E6%80%A5%E6%8C%AB%E9%80%BE8-%E6%8A%98%E8%AE%A9%E9%85%8D%E8%82%A1%E9%9B%86%E8%B5%84800%E4%BA%BF%E6%B8%AF%E5%85%83",
    },
    {
      id: 3,
      kind: "区域市场",
      kind_en: "Regional markets",
      market: "日本 / 韩国",
      title: "日经跌 0.74%，KOSPI 跌 3.12%",
      text: "日经 225 收于 65528.09 点，KOSPI 收于 6696.96 点。两市均下跌但幅度不同；本期仅记录已收盘指数，不把尚未核实的单一公司消息外推为整个市场的原因。",
      source_label: "每日经济新闻",
      source_url: "https://www.nbd.com.cn/articles/2026-08-21/4549687.html",
    },
    {
      id: 4,
      kind: "金融稳定",
      kind_en: "Financial stability",
      market: "非银行金融中介",
      title: "中植集团等 316 家企业进入实质合并破产清算程序",
      text: "北京一中院于 2026 年 4 月裁定中植集团等 316 家企业实质合并破产清算，6 月召开第一次债权人会议。这个程序性进展不是市场价格事件，却是理解财富管理、信托计划与底层资产处置如何相互连接的重要具体案例。",
      source_label: "全国企业破产重整案件信息网",
      source_url: "https://pccz.court.gov.cn/pcajxxw/pcgg/ggxq?id=727B8C7499347A0AEB16DABEB5108A4B",
    },
  ],
  companies: [
    {
      name: "阿里巴巴-W",
      ticker: "9988.HK",
      market: "香港",
      event: "配售融资与 AI 资本开支计划成为当日焦点",
      metrics: [
        { label: "配售价", value: "112.7 港元 / 股" },
        { label: "配售股数", value: "7.1 亿股" },
        { label: "融资规模", value: "约 800 亿港元（按报道口径）" },
        { label: "当日变动", value: "-8.54%" },
      ],
      note: "股权融资会同时改变资金用途预期与市场上的可交易股份供给。应把融资事实、公司对 AI 投入的表述与市场对未来回报的判断分开：前两项可由公告和交易条款验证，最后一项是市场定价。",
      source_label: "香港商报",
      source_url: "https://www.hkcd.com.hk/hkcdweb/content/2026/08/24/content_8771327.html",
    },
    {
      name: "中植企业集团（清算案例）",
      ticker: "未上市",
      market: "中国非银行金融中介",
      event: "实质合并破产清算中的资产处置与债权申报",
      metrics: [
        { label: "法院受理", value: "2024-01" },
        { label: "实质合并清算企业", value: "316 家" },
        { label: "第一次债权人会议", value: "2026-06" },
        { label: "公告列示资产类型", value: "信托计划、基金、资管计划、债券收益权等" },
      ],
      note: "这不是上市公司估值案例。它的教学价值在于展示：面向投资者的产品、管理与代销环节、以及期限和流动性不同的底层资产，最终会在破产程序中被还原为可核查的资产、债权与清偿顺序。具体回收率仍取决于后续清算和分配，不能预设。",
      source_label: "全国企业破产重整案件信息网",
      source_url: "https://pccz.court.gov.cn/pcajxxw/pcgg/ggxq?id=17b1300b2a344baf83b4df4931019e7e",
    },
  ],
  sources: [
    { label: "Financial Stability Board", title: "Non-bank Financial Intermediation", url: "https://www.fsb.org/work-of-the-fsb/financial-innovation-and-structural-change/non-bank-financial-intermediation/", published: "2026-02" },
    { label: "巴塞尔银行监管委员会", title: "Banks' interconnections with non-bank financial intermediaries", url: "https://www.bis.org/bcbs/publ/d598.htm", published: "2025-07-10" },
    { label: "全国企业破产重整案件信息网", title: "中植集团公司等 316 家企业实质合并破产清算案公告", url: "https://pccz.court.gov.cn/pcajxxw/pcgg/ggxq?id=727B8C7499347A0AEB16DABEB5108A4B", published: "2026-04-10" },
    { label: "全国企业破产重整案件信息网", title: "中植集团公司等 316 家企业资产、债权相关公告", url: "https://pccz.court.gov.cn/pcajxxw/pcgg/ggxq?id=17b1300b2a344baf83b4df4931019e7e", published: "2026-05" },
    { label: "新华财经", title: "三大指数放量调整，种业、黄金概念股走强", url: "https://www.cnfin.com/gs-lb/detail/20260824/4459430_1.html", published: "2026-08-24" },
    { label: "金融界", title: "港股收评：恒指跌 1.89%、科指跌 3.61%，阿里巴巴跌超 8%", url: "https://stock.jrj.com.cn/2026/08/24162858216444.shtml", published: "2026-08-24" },
    { label: "美联社", title: "How major US stock indexes fared Friday 8/21/2026", url: "https://apnews.com/article/09c079b43680c3e4564346892b5dc824", published: "2026-08-21" },
    { label: "新华财经", title: "伦敦股市 21 日上涨", url: "https://www.cnfin.com/gs-lb/detail/20260822/4458938_1.html", published: "2026-08-22" },
  ],
};
