import type { FinanceReport } from "../finance-types";

export const financeReport20260822: FinanceReport = {
  id: "2026-08-22",
  date: "2026-08-22",
  published_at: "2026-08-22T16:00:00+08:00",
  updated_at: "2026-08-22T16:00:00+08:00",
  edition_number: 1,
  draft: false,
  estimated_minutes: 18,
  ai_credit: { provider: "Z.ai", model: "GLM-5.3", role: "资料研究、事实核查与编辑协作" },
  market_as_of: "2026-08-21 收盘",
  title_zh: "当银行开始学着持有股权",
  title_en: "When banks learn to hold equity",
  dek: "本期学一个中国科创金融绕不开的机制——投贷联动：银行用股权的上行收益，补信贷覆盖不了的风险。再看上周五主要市场的表情：黄金创新高，A股缩量，医药回落，日经盘中跌逾九百点。",
  learning: {
    category: "概念",
    category_en: "Concept",
    title_zh: "投贷联动：当贷款的利息，覆盖不了科创的风险",
    title_en: "Investment-Loan Linkage: pricing startup risk with equity upside",
    standfirst: "科创企业轻资产、无抵押、高失败率，传统信贷的两样法宝——担保与利息——在它面前同时失灵。投贷联动的答案是：让银行在放贷之外拿一点股权，用少数项目的高成长，补多数项目的违约风险。",
    minutes: 9,
    blocks: [
      {
        heading: "它是什么",
        text: "投贷联动（Investment-Loan Linkage）指银行业金融机构以「信贷投放」与本集团设立的具有投资功能的子公司「股权投资」相结合的方式，为科创企业提供融资——这是 2016 年《指导意见》给出的狭义定义，核心是以股权投资收益抵补信贷风险，实现集团内风险与收益的平衡。实践中还有更宽松的广义形态：银行与外部 VC/PE 合作的「贷款+外部直投」，以及在贷款协议中附带认股权证（warrant），待企业成长后行权或转让分享增值。三种形态的共同逻辑只有一个——把「利息收不够」的部分，换成「股权上行」来收。",
      },
      {
        heading: "为什么需要它",
        text: "商业银行法限制银行直接持有企业股权，而科创企业的风险特征又恰恰与信贷逻辑错配：早期没有利润和抵押物，失败率高，但一旦成功回报巨大。纯债权定价下，银行收的利息封顶，承担的却是股权级的风险——收益与风险不对称，理性选择就是不给早期科创企业放贷。硅谷银行（SVB）最早系统性地解决了这个不对称：向创投圈企业放贷的同时大量索取认股权证，认股权收益长期是其重要的利润来源，也成了各国设计投贷联动时的商业原型。中国 2015 年提出探索、2016 年写入政府工作报告并启动试点，路径选择与这个国际先例直接相关——首批十家试点银行中就包括合资的浦发硅谷银行。",
      },
      {
        heading: "怎么做，怎么防风险",
        text: "2016 年 4 月，银监会、科技部、人民银行联合发布《关于支持银行业金融机构加大创新力度开展科创企业投贷联动试点的指导意见》，确定首批十家试点银行（国家开发银行、中国银行、恒丰银行、北京银行、天津银行、上海银行、汉口银行、西安银行、上海华瑞银行、浦发硅谷银行）与五个试点示范区（北京中关村、武汉东湖、上海张江、天津滨海、西安）。制度设计的关键词是「防火墙」：投资子公司只能用自有资金投资，不得用负债、代理或受托资金；投单一科创企业不超过子公司自有资金的 10%；子公司与母行实行机构隔离、资金隔离；贷款必须来自表内资金。此后监管思路持续演进——2021 年鼓励「贷款+外部直投」，2025 年《银行业保险业科技金融高质量发展实施方案》进一步将金融资产投资公司（AIC）股权投资试点有序扩围：从「集团内联动」走向「生态间合作」。",
      },
    ],
    case_study: {
      event: "一单落地，与一次倒闭",
      period: "2016-11 — 2023-03",
      text: "2016 年 11 月，国家开发银行与中关村科创企业北京仁创生态签订「投资+贷款」合同，3000 万元股权投资与 3000 万元贷款同日到位，成为全国首单落地的投贷联动项目——制度从文件走向资产负债表。六年多以后，商业原型 SVB 给出了另一面的注脚：2023 年 3 月，这家以投贷联动和认股权闻名的银行，因长期持有的大量债券在加息周期中产生巨额浮亏，叠加存款端高度集中于科创与创投圈层（客户高度同源、风险感知同步），挤兑在两天内将其压垮。SVB 的倒下不是投贷联动本身造成的，但它提醒了这种模式的每一个效仿者：股权收益能补信贷风险，补不了资产负债表的期限错配，更补不了客户结构同源带来的挤兑传染。",
    },
    pros: {
      label: "它的价值",
      items: [
        "风险-收益再平衡：用少数股权的高上行补多数贷款的违约损失，让银行「敢贷、早贷」",
        "企业融资组合更完整：债权+股权搭配，比纯 VC 融资稀释更少，比纯贷款可得性更高",
        "银行被迫深耕产业：股权视野倒逼信贷端建立科技企业风险识别能力，长期改善资产结构",
      ],
    },
    cons: {
      label: "它的风险与边界",
      items: [
        "风险传染：股权投资亏损可能穿透到集团，防火墙（自有资金、10% 上限、机构隔离）的执行质量决定模式成败",
        "期限错配：股权退出以年计，贷款以月计，SVB 的教训是错配叠加同源客户结构时，挤兑速度远超处置速度",
        "利益冲突：银行为促股权增值可能放松信贷标准，监管约束得住比例，约束不住尽调里的手",
      ],
    },
    takeaways: [
      "投贷联动的本质是把信贷「收不够」的风险溢价，换成股权期权来收",
      "看一家银行的投贷联动，先看防火墙（资金来源、持股上限、隔离安排），再看项目数量",
      "中国路径：从集团内子公司试点，到「贷款+外部直投」与 AIC 扩围——监管重心自始至终是隔离",
    ],
  },
  markets: [
    {
      id: "cn",
      region_zh: "中国内地",
      region_en: "China Mainland",
      as_of: "2026-08-21",
      indices: [
        { name: "上证指数", close: 3905.20, change_pct: 0.04, extra: "成交 8834 亿元" },
        { name: "深证成指", close: 14094.17, change_pct: 0.87, extra: "成交 9958 亿元" },
        { name: "创业板指", close: 3545.58, change_pct: 1.43, extra: "成交 4945 亿元" },
      ],
      commentary: "低开下探后震荡回升，三大指数集体收涨，但沪深京三市成交额降至 1.89 万亿元、较前日缩量约 2017 亿元。2505 只个股收涨、2862 只收跌，反弹没有得到量能确认。贵金属、锂矿、通信设备领涨，医药生物跌超 3%。",
    },
    {
      id: "hk",
      region_zh: "中国香港",
      region_en: "Hong Kong",
      as_of: "2026-08-21",
      indices: [
        { name: "恒生指数", close: 26009.46, change_pct: 1.21, extra: "主板成交 2572.8 亿港元" },
        { name: "国企指数", close: 8634.34, change_pct: 1.01 },
        { name: "恒生科技指数", close: 4766.16, change_pct: 1.40 },
      ],
      commentary: "高开高走，主板全天成交 2572.77 亿港元。黄金板块普涨，赤峰黄金涨超 12%；加密货币概念与 AI 大模型概念走强，博雅互动涨超 23%，MiniMax 涨超 11%，智谱涨超 10%。",
    },
    {
      id: "jp",
      region_zh: "日本",
      region_en: "Japan",
      as_of: "2026-08-21",
      indices: [
        { name: "日经 225", close: 66016.36, change_pct: -0.30 },
        { name: "东证指数（TOPIX）", close: 4067.29, change_pct: 0.19 },
      ],
      commentary: "受日美长期利率再次上升与中东局势影响，日经早盘一度下跌超过 900 点；午后随 KOSPI 转涨、AI 与半导体相关股票走强，跌幅收窄，东证指数翻红。海运、矿业领涨，医药品、精密机器偏弱。",
    },
    {
      id: "kr",
      region_zh: "韩国",
      region_en: "South Korea",
      as_of: "2026-08-21",
      indices: [
        { name: "KOSPI", close: 6912.95, change_pct: 0.88 },
      ],
      commentary: "KOSPI 收涨 0.88%。三星电子股东回报传闻升温（详见 Watchlist），半导体板块情绪受到提振，并对邻国市场形成外溢支撑——东京股市午后跌幅收窄即受其带动。",
    },
    {
      id: "us",
      region_zh: "美国",
      region_en: "United States",
      as_of: "2026-08-21（美东时间）",
      indices: [
        { name: "道琼斯工业指数", close: 53277.01, change_pct: 0.98 },
        { name: "标普 500", close: 7674.37, change_pct: 0.43 },
        { name: "纳斯达克综合指数", close: 26180.46, change_pct: 0.43 },
      ],
      commentary: "三大指数在周四回调后反弹收涨。此前一个交易日，财政部「救市」喊话的效果消退，三大指数曾收跌 0.87%—1.32%。存储与光通信板块表现顽强：SK 海力士公布巨额股东回报计划后，美光科技涨 3.97%；标普 500 十一大板块材料、医疗领涨。",
    },
    {
      id: "eu",
      region_zh: "欧洲",
      region_en: "Europe",
      as_of: "2026-08-21",
      indices: [
        { name: "英国富时 100", close: 10816.56, change_pct: 0.64 },
        { name: "德国 DAX", close: 26136.56, change_pct: 0.59 },
        { name: "法国 CAC 40", close: 8484.43, change_pct: 0.37 },
        { name: "欧洲斯托克 50", close: 6458.11, change_pct: 0.56 },
      ],
      commentary: "欧股四大基准全线收涨，富时 100 领涨。现货黄金同日上涨 1.88% 至 4604 美元/盎司，WTI 原油报 87.06 美元/桶——避险与通胀交易并存，与债市的谨慎形成对照。",
    },
  ],
  movers: [
    {
      id: 1,
      kind: "商品异动",
      kind_en: "Commodities",
      market: "全球",
      title: "现货黄金涨 1.88% 至 4604 美元，黄金股两地共振",
      text: "现货黄金周五上涨 1.88% 报 4604.09 美元/盎司，COMEX 黄金期货涨 1.97% 报 4661.60 美元。港股赤峰黄金涨超 12%、山东黄金涨超 8%、老铺黄金涨超 7%；A股湖南白银、白银有色、融捷股份等涨停。中东局势与美债抛压下，避险需求是共同解释。",
      source_label: "证券时报",
      source_url: "https://stcn.com/article/detail/4096403.html",
    },
    {
      id: 2,
      kind: "量能信号",
      kind_en: "Volume",
      market: "A股",
      title: "三市成交额跌破 2 万亿，缩量反弹待确认",
      text: "沪深京三市成交 18924 亿元，较前日缩量约 2017 亿元，为近期首次跌破 2 万亿。两融余额截至 8 月 20 日约 2.67 万亿元、近两日略有回落。受访机构认为量能能否重返 2 万亿上方是情绪修复的核心观察指标。",
      source_label: "证券时报",
      source_url: "https://www.stcn.com/article/detail/4099548.html",
    },
    {
      id: 3,
      kind: "板块异动",
      kind_en: "Sector",
      market: "A股",
      title: "医药生物板块全线下挫，单日跌超 3%",
      text: "化学制药、创新药、中药生产、医疗服务全线下跌，医药生物板块单日跌超 3%，为当日最弱一级行业；农业、美容护理、食品饮料、房地产跌幅亦超 1%。31 个申万一级行业仅 16 个收红。",
      source_label: "中国新闻网",
      source_url: "https://www.chinanews.com/cj/2026/08-21/10681746.shtml",
    },
    {
      id: 4,
      kind: "股东回报",
      kind_en: "Capital Return",
      market: "韩股/美股",
      title: "三星 150 万亿韩元回报传闻，存储板块跨市场走强",
      text: "市场传闻三星电子股东回报总额一天之内从 100 万亿韩元上调至 150 万亿韩元（约合人民币 7233 亿元），且与专注回购注销的 SK 海力士不同，三星可能以巨额特别分红形式落地。SK 海力士周四逆势涨 4.43%，美光科技涨 3.97%，迈威尔科技涨 5.79%。",
      source_label: "财联社",
      source_url: "https://www.163.com/dy/article/L4R7NV7605198CJN.html",
    },
    {
      id: 5,
      kind: "个股异动",
      kind_en: "Mover",
      market: "港股",
      title: "恒基地产涨 7.17%，本地地产股集体走强",
      text: "恒基地产收涨 7.17% 报 30.2 港元，新鸿基地产涨 2.81%，长实集团涨 1.63%。中资金融同步上涨：中国平安涨 3.88%，中国人寿涨 5.09%。",
      source_label: "新华社",
      source_url: "https://english.news.cn/20260821/07b115774c9f4fe89c4ede3ca6cc0eaa/c.html",
    },
    {
      id: 6,
      kind: "盘中最深跌幅",
      kind_en: "Intraday",
      market: "日股",
      title: "日经盘中跌逾 900 点，尾盘收窄至 0.30%",
      text: "日美长期利率再度上升叠加中东局势，东京股市早盘多数股票遭抛售，日经一度下挫超过 900 点；午后 KOSPI 转涨带动 AI、半导体相关股票回升，跌幅显著收窄，东证指数收涨 0.19%。",
      source_label: "新华财经",
      source_url: "https://www.toutiao.com/article/7676394693889901090",
    },
  ],
  companies: [
    {
      name: "阿里巴巴",
      ticker: "BABA · NYSE",
      market: "美股",
      event: "财报后低开高走，AI 资本开支表态扭转盘面",
      metrics: [
        { label: "盘中表现", value: "开盘一度跌超 5%，随后持续拉升" },
        { label: "收盘", value: "逆势收涨超 1%（周四）" },
        { label: "管理层表态", value: "AI 算力 CAPEX「回报确定性非常高」" },
        { label: "回报周期", value: "称可在 3 年之内回本，未来还会持续缩短" },
      ],
      note: "针对 Michael Burry 唱空算力经济学，管理层举例称 2020 年购买的 A100、2018 年购买的 V100 至今仍近乎满载运转。口径是管理层的，兑现要看后续季度的 capex 与云收入。",
      source_label: "财联社",
      source_url: "https://www.163.com/dy/article/L4R7NV7605198CJN.html",
    },
    {
      name: "三星电子",
      ticker: "005930 · KRX",
      market: "韩股",
      event: "巨额股东回报传闻：100 → 150 万亿韩元",
      metrics: [
        { label: "传闻规模", value: "一天内自 100 万亿韩元上调至 150 万亿韩元" },
        { label: "折合人民币", value: "约 7233 亿元" },
        { label: "形式差异", value: "SK 海力士为回购注销，三星或推特别分红" },
        { label: "板块联动", value: "SK 海力士 +4.43%，美光 +3.97%（周四）" },
      ],
      note: "截至发稿仍为传闻而非公司公告，数字在一日内两次变化本身就是信息。留意后续正式披露的形式与分期安排——分红与回购对股价与现金流的含义并不相同。",
      source_label: "财联社",
      source_url: "https://www.163.com/dy/article/L4R7NV7605198CJN.html",
    },
  ],
  sources: [
    { label: "人民网", title: "投贷联动首批试点地区和银行明确", url: "https://money.people.com.cn/bank/BIG5/n1/2016/0422/c202331-28296099.html", published: "2016-04-22" },
    { label: "中国金融新闻网", title: "「投贷联动」支持新质生产力发展的思考", url: "https://www.financialnews.com.cn/2025-07/30/content_430386.html", published: "2025-07-30" },
    { label: "中证网", title: "投贷联动试点稳步推进（政策时间线）", url: "https://cs.com.cn/xwzx/201710/t20171030_5541024.html", published: "2017-10-30" },
    { label: "新华社", title: "纽约股市三大股指21日上涨", url: "https://www.163.com/dy/article/L4TLCGQP05346RC6.html", published: "2026-08-22" },
    { label: "证券时报网", title: "A股成交量跌破2万亿元，通信、有色走强，下周怎么走？", url: "https://www.stcn.com/article/detail/4099548.html", published: "2026-08-21" },
    { label: "新华社", title: "Hong Kong stocks close higher", url: "https://english.news.cn/20260821/07b115774c9f4fe89c4ede3ca6cc0eaa/c.html", published: "2026-08-21" },
    { label: "新华财经", title: "东京股市两大股指涨跌互现", url: "https://www.toutiao.com/article/7676394693889901090", published: "2026-08-21" },
    { label: "财联社", title: "美股收盘：贝森特「救市」有效期仅持续一天", url: "https://www.163.com/dy/article/L4R7NV7605198CJN.html", published: "2026-08-21" },
    { label: "中国新闻网", title: "A股收评：三大指数集体收涨，超2800只个股飘绿", url: "https://www.chinanews.com/cj/2026/08-21/10681746.shtml", published: "2026-08-21" },
    { label: "中国基金报", title: "日韩股市收盘表现分化", url: "https://www.chnfund.com/article/08799fa4-1f5c-59b4-5367-3a233531ea9c", published: "2026-08-21" },
  ],
};
