import type { FinanceReport } from "../finance-types";

export const financeReport20260826: FinanceReport = {
  id: "2026-08-26",
  date: "2026-08-26",
  published_at: "2026-08-26T19:30:00+08:00",
  updated_at: "2026-08-26T19:30:00+08:00",
  edition_number: 4,
  draft: false,
  estimated_minutes: 18,
  ai_credit: { provider: "OpenAI", model: "GPT5.6Luna", role: "资料研究、事实核查与编辑协作" },
  market_as_of: "2026-08-26 19:30（北京时间；本期各市场均采用截至该时点可核实的 8 月 25 日最近完整收盘）",
  title_zh: "M0、M1、M2：货币到底有多少，大水漫灌又是什么意思",
  title_en: "M0, M1 and M2: measuring money and understanding broad liquidity",
  dek: "货币量不是一只装满现金的水桶，而是按流动性和发行部门负债划分的统计集合。本期从 M0、M1、M2 的口径出发，说明商业银行如何通过资产负债表创造存款，再解释“大水漫灌”为什么不是简单地印钞，以及判断宽松是否有效要看哪些传导环节。",
  learning: {
    category: "货币与货币政策",
    category_en: "Money & monetary policy",
    title_zh: "M0、M1、M2：从现金到广义购买力",
    title_en: "M0, M1 and M2: from cash to broad purchasing power",
    standfirst: "货币量是某一时点的存量，不是某一天“印了多少钱”的流量。不同国家口径略有差异；在中国的常用口径中，M0 是流通中现金，M1 在 M0 基础上加入更易用于交易的活期存款，M2 再加入定期等较不流动的存款。层级越宽，包含的金融资产越多，但不代表它们都能同样快地用于消费。",
    minutes: 9,
    blocks: [
      { heading: "第一步：先分清三个层级", text: "M0 是流通中货币，最接近公众手中的现金；M1 是 M0 加上单位和个人活期存款以及按现行统计口径计入的非银行支付机构客户备付金，主要观察现实购买力；M2 是 M1 加上单位和个人定期存款及其他存款，反映更广的潜在购买力。公式可以写成：M1 = M0 + 活期类存款；M2 = M1 + 定期及其他存款。它们是统计口径，不是三种彼此独立的钱。" },
      { heading: "第二步：钱主要怎样被创造", text: "央行货币包括现金和商业银行在央行的准备金；商业银行货币主要是银行负债端的存款。当银行发放一笔贷款时，通常同时增加一项贷款资产和一项客户存款负债，存款因此被创造；贷款归还时，相应存款也会收缩。央行降准、公开市场操作或降低政策利率可以改善银行体系的流动性和融资条件，但不等于每一元准备金都会自动变成一元新增贷款。" },
      { heading: "第三步：货币乘数不是机械按钮", text: "教科书常用货币乘数 m = 1 / 准备金率 来说明存款扩张的可能上限，但现实中银行受资本充足率、流动性监管、借款人信用、风险偏好和有效需求约束。银行有准备金，不代表一定愿意放贷；企业有授信，也不代表一定愿意投资。现代体系里，央行往往先通过利率和资产负债表提供条件，银行贷款与公众持币行为再共同决定广义货币变化。" },
      { heading: "“大水漫灌”具体在说什么", text: "“大水漫灌”是一个政策批评性比喻，通常指不区分部门和风险、以过度宽松的流动性或信用扩张普遍推升需求。它可能通过低利率、降准、再贷款、资产购买或财政与金融协同等渠道发生。问题不在于每次宽松都错误，而在于资金是否进入生产、就业和可持续投资；如果资金更多停留在资产交易、低效项目或高杠杆链条，可能推高资产价格、汇率压力和未来坏账，而没有形成相称的实际产出。" },
    ],
    case_study: {
      event: "同样的 M2 增长，为什么体感可以完全不同",
      period: "概念案例；用 2026 年货币政策观察框架解释",
      text: "假设 M2 增长 10%，但其中相当一部分来自企业和居民把资金从活期转入定期，M2 会上升而 M1 可能走弱，说明资金更偏向储蓄而非即时交易。另一种情形是银行贷款扩张、企业活期存款和支付活动同步增加，M1 与 M2 一起走强，名义需求的传导可能更直接。两种情形的 M2 增速相同，经济含义却不同。因此不能只看“水量”，还要看水在谁的账户、以什么期限、通过什么信用链条流动。",
    },
    pros: { label: "宽松政策能解决什么", items: ["降低融资成本，缓解流动性紧张和信用市场的突然收缩", "在需求不足时支持企业周转、居民消费和公共投资", "通过利率和资产负债表工具稳定支付系统与金融机构预期"] },
    cons: { label: "为什么不能只靠放水", items: ["没有有效需求时，准备金可能停留在银行体系或转成低风险储蓄", "信用扩张过快会推高资产价格、杠杆和期限错配", "退出过慢可能带来通胀、汇率、资本流动和未来坏账压力"] },
    takeaways: [
      "M0、M1、M2 是按流动性分层的统计口径，越宽不等于越能立刻消费。",
      "商业银行贷款会创造存款；货币乘数只能说明机制，不能预测现实中的固定倍数。",
      "判断“大水漫灌”不能只看 M2，要同时看 M1、信贷投向、资产价格、通胀和实体需求。",
    ],
  },
  markets: [
    { id: "cn", region_zh: "中国内地", region_en: "China Mainland", as_of: "2026-08-25 收盘（最近完整交易日）", indices: [{ name: "上证指数", close: 3889.45, change_pct: 0.19 }], commentary: "公开收盘数据显示上证指数温和上涨；指数变化只描述交易结果，不单独证明货币政策或某一新闻是唯一原因。" },
    { id: "hk", region_zh: "中国香港", region_en: "Hong Kong", as_of: "2026-08-25 收盘（最近完整交易日）", indices: [{ name: "恒生指数", close: 25511.10, change_pct: -0.02 }], commentary: "港股接近持平；融资、利率和公司资本开支预期需要分开观察。" },
    { id: "jp", region_zh: "日本", region_en: "Japan", as_of: "2026-08-25 收盘（最近完整交易日）", indices: [{ name: "日经 225", close: 65856.43, change_pct: 0.50 }], commentary: "日经上涨时，仍需区分指数权重股、汇率和海外科技股表现。" },
    { id: "kr", region_zh: "韩国", region_en: "South Korea", as_of: "2026-08-25 收盘（最近完整交易日）", indices: [{ name: "KOSPI", close: 6742.74, change_pct: 0.68 }], commentary: "KOSPI 盘中一度明显下挫后收高；韩国市场对半导体与出口公司权重较高，指数变化不能直接代表所有企业。" },
    { id: "us", region_zh: "美国", region_en: "United States", as_of: "2026-08-25 收盘（最近完整交易日）", indices: [{ name: "道琼斯工业指数", close: 53577.40, change_pct: 0.30 }, { name: "标普 500", close: 7677.28, change_pct: 0.30 }, { name: "纳斯达克综合指数", close: 26151.30, change_pct: 0.70 }], commentary: "油价回落和收益率下降帮助缓解债券市场压力，科技股在 Nvidia 财报前反弹；这仍是市场描述，不是单一因果结论。" },
    { id: "eu", region_zh: "欧洲", region_en: "Europe", as_of: "2026-08-25 收盘（最近完整交易日）", indices: [{ name: "英国富时 100", close: 10854.60, change_pct: 0.29 }, { name: "德国 DAX", close: 26206.00, change_pct: 0.61 }, { name: "法国 CAC 40", close: 8499.20, change_pct: -0.16 }], commentary: "欧洲基准指数分化；市场仍在评估能源、制裁与利率路径。" },
  ],
  movers: [
    { id: 1, kind: "货币政策", kind_en: "Monetary policy", market: "全球", title: "市场等待数据与 Nvidia 财报，流动性预期仍是定价背景", text: "8 月 25 日的全球市场报道显示，投资者在等待重要宏观数据和 Nvidia 财报；收益率回落、油价走弱与美国对伊朗相关制裁威胁共同影响风险偏好。事件之间存在相关性，但不能把单日指数变化归因于单一变量。", source_label: "Reuters / Investing.com", source_url: "https://www.investing.com/news/commodities-news/morning-bid-economic-salvos-4874888" },
    { id: 2, kind: "市场结构", kind_en: "Market structure", market: "亚太", title: "亚洲市场 8 月 25 日多数温和变化", text: "亚洲市场报道显示，韩国 KOSPI 反弹约 0.68%，恒生指数接近持平，投资者关注 Jackson Hole、地缘政治与科技股估值。市场表现提供的是结果，不是货币量变化的直接证明。", source_label: "Asia Market Wrap", source_url: "https://edgeconsultancykw.com/asia-market-wrap-25-august-2026/" },
    { id: 3, kind: "流动性", kind_en: "Liquidity", market: "美国 / 欧洲", title: "油价走弱与收益率回落改变风险资产的折现背景", text: "Reuters 8 月 25 日市场综述称，全球股票指标上涨、收益率下降，油价因制裁消息而走弱。对货币政策学习而言，这提醒我们区分央行流动性、市场利率和风险溢价三个不同变量。", source_label: "Reuters / LSE", source_url: "https://www.lse.co.uk/news/global-markets-equities-rise-with-tech-boost-and-yields-fall-with-oil-prices-fdzn20xom7uepsn.html" },
  ],
  companies: [
    { name: "Nvidia", ticker: "NVDA", market: "美国", event: "财报成为全球科技股的重要观察点", metrics: [{ label: "观察窗口", value: "8 月 25 日市场等待后续财报" }, { label: "关联主题", value: "AI 资本开支与科技估值" }], note: "财报预期会影响风险偏好，但不能把公司业绩预期等同于广义货币变化。", source_label: "Reuters / Investing.com", source_url: "https://www.investing.com/news/commodities-news/morning-bid-economic-salvos-4874888" },
  ],
  sources: [
    { label: "中国人民银行", title: "狭义货币和广义货币", url: "https://www.pbc.gov.cn/rmyh/109339/2025080818580470423/index.html", published: "2025-03-10" },
    { label: "欧洲央行", title: "What are monetary aggregates?", url: "https://data.ecb.europa.eu/methodology/what-are-monetary-aggregates", published: "2026-06" },
    { label: "欧洲央行", title: "What is money?", url: "https://www.ecb.europa.eu/ecb-and-you/explainers/tell-me-more/html/what_is_money.en.html", published: "长期教育资料" },
    { label: "美联社", title: "How major US stock indexes fared Tuesday 8/25/2026", url: "https://apnews.com/article/69aae9f2f61737936f126e7820833bbe", published: "2026-08-25" },
    { label: "FRED / Nikkei Indexes", title: "Nikkei Stock Average, Nikkei 225", url: "https://fred.stlouisfed.org/series/NIKKEI225/", published: "2026-08-25" },
    { label: "韩联社", title: "Seoul stocks end higher ahead of Nvidia earnings", url: "https://en.yna.co.kr/view/AEN20260825007351320?section=economy-finance%2Feconomy", published: "2026-08-25" },
    { label: "SPFutures", title: "World Markets", url: "https://spfutures.org/world-markets/", published: "2026-08-25" },
    { label: "Reuters / LSE", title: "Global markets: equities rise with tech boost", url: "https://www.lse.co.uk/news/global-markets-equities-rise-with-tech-boost-and-yields-fall-with-oil-prices-fdzn20xom7uepsn.html", published: "2026-08-25" },
    { label: "Asia Market Wrap", title: "Nine of 11 benchmarks rise before Nvidia earnings", url: "https://edgeconsultancykw.com/asia-market-wrap-25-august-2026/", published: "2026-08-25" },
  ],
};
