import type { FinanceReport } from "../finance-types";

export const financeReport20260829: FinanceReport = {
  id: "2026-08-29",
  date: "2026-08-29",
  published_at: "2026-08-29T11:20:00+08:00",
  updated_at: "2026-08-29T11:20:00+08:00",
  edition_number: 6,
  draft: false,
  estimated_minutes: 20,
  ai_credit: { provider: "OpenAI", model: "GPT5.6Sol", role: "资料研究、事实核查与编辑协作" },
  market_as_of: "2026-08-29 11:10（北京时间；采用中国内地、中国香港、日本、韩国、欧洲和美国市场 8 月 28 日的完整收盘）",
  title_zh: "股票分红：收到现金以后，你真的变得更富了吗",
  title_en: "Stock dividends: cash income, ex-dividend mechanics and total return",
  dek: "分红把公司账上的现金交到股东手中，却不会在支付的一刻凭空创造价值。本期从宣告日、除息日、股权登记日和支付日讲起，解释股息率与派息率怎样计算、为什么高股息可能是警报，以及一周交易结束后应如何把现金分红、回购和股价变化放进同一张总回报账单。",
  learning: {
    category: "公司金融与股东回报",
    category_en: "Corporate finance & shareholder returns",
    title_zh: "从一笔股息，看懂公司的现金分配",
    title_en: "Reading corporate cash allocation through dividends",
    standfirst: "现金分红是董事会把公司的一部分可分配现金按持股数量交给股东。它通常来自经营积累，但并非合同保证：盈利、现金流、负债、投资机会和董事会决定都会影响下一次派息。评价分红不能只看到账金额，而要同时看除息后的价格、税费、再投资效果以及公司剩余资本能否继续创造回报。",
    minutes: 11,
    blocks: [
      {
        heading: "第一步：分红是资产负债表里的现金转移",
        text: "公司支付每股股息后，现金资产和股东权益会相应减少，股东账户则收到现金。若其他条件不变，企业价值会因离开公司的现金而下降。因此，分红是把既有价值从公司内部移到股东手中，不是公司和股东同时多出同一笔钱。成熟企业缺少高回报再投资机会时，稳定分红可能是合理的资本配置；成长企业若能把现金投入高回报项目，不分红也不必然损害股东。",
      },
      {
        heading: "四个日期：什么时候买入才能拿到这次股息",
        text: "宣告日是董事会公布股息金额和时间表的日期；股权登记日用于确定名册上的合资格股东；除息日开始，股票交易价格不再包含本次股息权利；支付日才是现金实际发放的日期。以美国普通现金股息的一般规则为例，在除息日或之后买入，通常拿不到这一期股息；在除息日前持有才保留权利。不同市场、特殊大额股息和股票股息可能采用不同安排，最终应以交易所和发行人公告为准。",
      },
      {
        heading: "除息为什么不是无风险套利",
        text: "假设股票除息前为 10 元，每股派现 0.50 元。忽略市场波动和税费，除息后的理论参考价格约为 9.50 元：投资者从一项价值 10 元的股票，变成价值约 9.50 元的股票加 0.50 元现金，总财富仍约为 10 元。现实价格还会受业绩、利率和交易情绪影响，因此不会机械地刚好下跌 0.50 元；但只为领取股息而在除息前买入，并没有自动锁定收益。",
      },
      {
        heading: "三个指标：股息率、派息率与现金覆盖",
        text: "股息率 = 过去或预计一年每股股息 ÷ 当前股价，用来衡量现金收益相对价格的比例；派息率 = 普通股股息 ÷ 归母净利润，用来观察利润有多少被分出；自由现金流派息率 = 股息 ÷ 自由现金流，更接近现金是否真正覆盖派息。利润受会计项目影响，现金流也会因资本开支而波动，所以三项指标要结合多年记录、净负债、利息负担和行业周期判断。股价急跌会被动推高股息率，高数字有时反而反映市场预期减配或停配。",
      },
      {
        heading: "把分红、回购和留存收益放进总回报",
        text: "投资者的总回报近似等于股价回报加现金分红，并在更严谨的比较中假设分红再投资。公司还可通过回购减少流通股，把现金返还给愿意卖出的股东；回购更灵活，但若价格过高、同时大量举债，可能毁损价值。分红提供可见现金流，回购改变每股指标，留存收益则把资本继续放在公司内部。好的资本配置没有固定答案，关键是每一元现金放在哪里能产生更高的风险调整后回报。",
      },
    ],
    case_study: {
      event: "英伟达：高增长公司如何同时分红与回购",
      period: "截至 2026 年 7 月 26 日的 2027 财年第二季度；公告于 2026 年 8 月 26 日",
      text: "英伟达报告季度收入 962 亿美元、同比增长 106%，并称该季度通过股票回购和现金分红向股东返还约 260 亿美元；下一季度现金股息为每股 0.25 美元，登记日为 9 月 10 日、支付日为 10 月 1 日。这个案例说明，判断股东回报不能只看股息率：对股价较高、仍在快速增长的公司，现金股息可能只占很小部分，回购和留存收益的使用效率同样重要。公告披露的是返还规模和计划，不保证未来股息或股价表现。",
    },
    pros: {
      label: "分红为什么有价值",
      items: [
        "把企业现金直接交给股东，减少管理层长期囤积低回报资本的空间",
        "稳定派息可为需要现金流的投资者提供较可预测的收入来源",
        "连续且有现金流覆盖的分红，能检验利润是否最终转化为可分配现金",
      ],
    },
    cons: {
      label: "高股息策略容易忽略什么",
      items: [
        "除息会降低股票所含的现金价值，领取股息本身不是无风险套利",
        "股息可能被削减；高收益率可能来自股价暴跌、负债上升或盈利恶化",
        "税费、汇率和再投资时点会改变实际到手收益，不同账户与市场规则也不同",
      ],
    },
    takeaways: [
      "先看总回报，再看股息率；分红只是股东回报的一部分。",
      "高股息率必须由利润、自由现金流和稳健资产负债表共同支撑。",
      "除息前买入并不会凭空获得股息，交易价格会反映已经离开公司的现金。",
      "比较分红股时使用多年数据，并把回购、债务和再投资机会一起纳入资本配置分析。",
    ],
  },
  markets: [
    {
      id: "cn",
      region_zh: "中国内地",
      region_en: "China Mainland",
      as_of: "2026-08-28 收盘",
      indices: [{ name: "上证指数", close: 3952.18, change_pct: -0.11, extra: "本周 +1.20%" }],
      commentary: "上证指数周五小幅回落，但全周上涨 1.20%。周内指数上行并不意味着所有板块同步受益，分红投资仍需区分现金流稳定行业与周期性高收益率。",
    },
    {
      id: "hk",
      region_zh: "中国香港",
      region_en: "Hong Kong",
      as_of: "2026-08-28 收盘",
      indices: [{ name: "恒生指数", close: 25584.79, change_pct: 0.07, extra: "本周 -1.63%" }],
      commentary: "恒生指数周五近乎持平，全周下跌 1.63%；恒生科技指数周五另跌 0.33%。高股息金融、电信和能源股与科技成长股的驱动不同，不能用同一估值框架简单排序。",
    },
    {
      id: "jp",
      region_zh: "日本",
      region_en: "Japan",
      as_of: "2026-08-28 收盘",
      indices: [{ name: "日经 225", close: 66405.56, change_pct: 0.41, extra: "本周 +0.59%" }],
      commentary: "日经 225 周五与全周均上涨。观察日本股东回报时，应把公司治理改善、交叉持股处置、回购和现金分红放在一起，而不是只比较静态股息率。",
    },
    {
      id: "kr",
      region_zh: "韩国",
      region_en: "South Korea",
      as_of: "2026-08-28 收盘",
      indices: [{ name: "KOSPI", close: 6788.79, change_pct: -1.79, extra: "本周 -1.80%" }],
      commentary: "KOSPI 周五明显下跌，全周跌 1.80%。半导体权重使指数对全球科技周期更敏感；周期高点的利润和股息不能直接外推为长期水平。",
    },
    {
      id: "us",
      region_zh: "美国",
      region_en: "United States",
      as_of: "2026-08-28 收盘",
      indices: [
        { name: "道琼斯工业指数", close: 53559.99, change_pct: -0.02, extra: "本周 +0.5%" },
        { name: "标普 500", close: 7711.76, change_pct: -0.25, extra: "本周 +0.5%" },
        { name: "纳斯达克综合指数", close: 26402.42, change_pct: -0.52, extra: "本周 +0.8%" },
      ],
      commentary: "美股周五小幅回落，但三大指数全周仍上涨。英伟达财报支持科技股，而市场对利率路径的重新评估限制了周五风险偏好；单周上涨不能替代对估值与现金回报的判断。",
    },
    {
      id: "eu",
      region_zh: "欧洲",
      region_en: "Europe",
      as_of: "2026-08-28 收盘",
      indices: [{ name: "STOXX Europe 600", close: 655.16, change_pct: 0.51, extra: "本周约 +0.15%" }],
      commentary: "欧洲股市周五反弹，全周温和上涨，结束此前连续两周下跌。法国银行股在前一日下挫后回升，说明高分红金融股仍会受到财政预期、利率和资产质量共同影响。",
    },
  ],
  movers: [
    {
      id: 1,
      kind: "股东回报",
      kind_en: "Shareholder returns",
      market: "美国",
      title: "英伟达一季返还约 260 亿美元，回购远比每股股息更能解释规模",
      text: "英伟达在 8 月 26 日财报中披露，季度内以回购和现金分红合计返还约 260 亿美元，并宣布下一季度每股派息 0.25 美元。把两种方式合并观察，比单看股息率更能说明公司的资本分配。",
      source_label: "NVIDIA Newsroom",
      source_url: "https://nvidianews.nvidia.com/news/nvidia-announces-financial-results-for-second-quarter-fiscal-2027",
    },
    {
      id: 2,
      kind: "周度市场",
      kind_en: "Weekly markets",
      market: "美国",
      title: "三大指数周线收涨，周五却因利率预期而降温",
      text: "标普 500、道指和纳指本周分别上涨约 0.5%、0.5%和 0.8%，但周五均回落。收益率与政策利率预期会改变股票未来现金流的折现价值，也会影响高股息资产相对债券的吸引力。",
      source_label: "Associated Press",
      source_url: "https://apnews.com/article/3f3477bcea915ac53ec2ae905ae57919",
    },
    {
      id: 3,
      kind: "区域分化",
      kind_en: "Regional divergence",
      market: "亚洲",
      title: "中国内地与日本周线收涨，香港与韩国回落",
      text: "上证指数和日经 225 本周分别上涨 1.20%和 0.59%，恒生指数和 KOSPI 分别下跌 1.63%和 1.80%。同一周内方向分化，提醒投资者不要把“高股息”当作跨市场通用的低波动标签。",
    },
    {
      id: 4,
      kind: "欧洲市场",
      kind_en: "European markets",
      market: "欧洲",
      title: "STOXX 600 周五反弹，周线仅温和上行",
      text: "STOXX Europe 600 周五上涨 0.51%至 655.16 点，按前后周五收盘计算全周约涨 0.15%。法国银行股反弹，但法国财政与增长忧虑仍是金融股估值的一部分。",
      source_label: "Reuters / Yahoo Finance",
      source_url: "https://finance.yahoo.com/markets/world-indices/articles/european-shares-rise-french-stocks-162928091.html",
    },
  ],
  companies: [
    {
      name: "NVIDIA",
      ticker: "NVDA",
      market: "美国",
      event: "第二季度业绩与股东回报计划",
      metrics: [
        { label: "季度收入", value: "962 亿美元，同比 +106%" },
        { label: "数据中心收入", value: "890 亿美元，同比 +117%" },
        { label: "季度股东返还", value: "约 260 亿美元（回购与现金分红合计）" },
        { label: "下一季度股息", value: "每股 0.25 美元；10 月 1 日支付" },
      ],
      note: "较小的每股现金股息与大规模回购并存，显示股息率不能独立代表总股东回报；未来返还仍取决于董事会决定、经营现金流与资本需求。",
      source_label: "NVIDIA Newsroom",
      source_url: "https://nvidianews.nvidia.com/news/nvidia-announces-financial-results-for-second-quarter-fiscal-2027",
    },
  ],
  sources: [
    {
      label: "SEC Investor.gov",
      title: "Ex-Dividend Dates: When Are You Entitled to Stock and Cash Dividends",
      url: "https://www.investor.gov/introduction-investing/investing-basics/glossary/ex-dividend-dates-when-are-you-entitled-stock-and",
      published: "2026-03 更新示例",
    },
    {
      label: "SEC Investor.gov",
      title: "Fund Distributions — Investor Bulletin",
      url: "https://www.investor.gov/introduction-investing/general-resources/news-alerts/alerts-bulletins/investor-bulletins/fund-distributions-investor-bulletin",
      published: "2026-08-19",
    },
    {
      label: "S&P Dow Jones Indices",
      title: "Methodology Matters",
      url: "https://www.spglobal.com/spdji/en/research-insights/index-literacy/methodology-matters/",
      published: "2026",
    },
    {
      label: "NVIDIA Newsroom",
      title: "NVIDIA Announces Financial Results for Second Quarter Fiscal 2027",
      url: "https://nvidianews.nvidia.com/news/nvidia-announces-financial-results-for-second-quarter-fiscal-2027",
      published: "2026-08-26",
    },
    {
      label: "Associated Press",
      title: "How major US stock indexes fared Friday 8/28/2026",
      url: "https://apnews.com/article/3f3477bcea915ac53ec2ae905ae57919",
      published: "2026-08-28",
    },
    {
      label: "Investing.com",
      title: "Shanghai Composite historical data",
      url: "https://hk.investing.com/indices/shanghai-composite-historical-data",
      published: "2026-08-28",
    },
    {
      label: "新华社",
      title: "港股28日涨0.07% 收报25584.79点",
      url: "https://www.news.cn/20260828/4baaa1a81b8b4f47b4f2fb11b639bcbb/c.html",
      published: "2026-08-28",
    },
    {
      label: "财联社 / 新浪财经",
      title: "日韩股市收盘涨跌不一",
      url: "https://finance.sina.com.cn/roll/2026-08-28/doc-inipwait8954332.shtml",
      published: "2026-08-28",
    },
    {
      label: "Reuters / Yahoo Finance",
      title: "European shares rise as French stocks rebound; markets digest Warsh speech",
      url: "https://finance.yahoo.com/markets/world-indices/articles/european-shares-rise-french-stocks-162928091.html",
      published: "2026-08-28",
    },
  ],
};
