import type { FinanceReport } from "../finance-types";

export const financeReport20260831: FinanceReport = {
  id: "2026-08-31",
  date: "2026-08-31",
  published_at: "2026-08-31T17:20:00+08:00",
  updated_at: "2026-08-31T17:34:55+08:00",
  edition_number: 7,
  draft: false,
  estimated_minutes: 21,
  ai_credit: { provider: "OpenAI", model: "GPT5.6Sol", role: "资料研究、事实核查与编辑协作" },
  market_as_of: "2026-08-31 17:20（北京时间；亚洲市场采用 8 月 31 日完整收盘，欧洲与美国采用 8 月 28 日最近完整收盘）",
  title_zh: "增长、通胀与就业：宏观经济为什么不能只看一个数字",
  title_en: "Growth, inflation and jobs: reading the macroeconomy as a system",
  dek: "GDP、物价和失业率不是三张互不相干的成绩单，而是一套会彼此反馈的系统。本期从国民收入恒等式讲起，解释真实增长与名义增长、价格水平与通胀率、就业与劳动参与率的区别，并用中国 8 月 PMI 和美国最新增长、通胀与就业数据，搭建一张可重复使用的宏观经济仪表盘。",
  learning: {
    category: "宏观经济学基础",
    category_en: "Macroeconomics fundamentals",
    title_zh: "别追逐一个数字：用四步读懂宏观经济",
    title_en: "Beyond one headline number: a four-step macro framework",
    standfirst: "宏观经济学研究的是总产出、总体价格、就业和跨部门资金流动。它关心的不只是经济有没有增长，还关心增长来自哪里、价格是否侵蚀购买力、劳动者是否真正参与其中，以及政策为了稳定一个目标会不会牺牲另一个目标。任何单项数据都只是切面；方向、速度、结构和政策约束合起来，才构成可以行动的判断。",
    minutes: 13,
    blocks: [
      {
        heading: "第一步：GDP 是总量账户，不是幸福指数",
        text: "支出法把国内生产总值写成 Y = C + I + G + NX，即居民消费、投资、政府购买与净出口之和。这是会计恒等式，用来确认最终需求落在哪里，并不自动说明哪一项变化造成了增长。读 GDP 至少要区分名义值和剔除价格变化后的真实值、总量和人均量、同比和环比年化，也要观察存货、进口和政府支出是否放大了表面波动。美国二季度真实 GDP 按年率增长 1.5%，但私人国内最终销售增长 4.2%；同一份报告中的两个数字回答的是不同问题：前者描述总体产出，后者更聚焦私人消费与固定投资形成的国内需求。",
      },
      {
        heading: "第二步：价格水平上涨，不等于通胀还在加速",
        text: "通胀率衡量价格水平的变化速度。通胀从 5% 降到 3%，意味着价格仍在上涨，只是涨得慢了；只有价格水平下降才叫通缩。总体通胀贴近家庭实际账单，核心通胀剔除波动较大的食品和能源，更便于观察持续性，但两者都不能单独代表每个家庭的体验。还要把名义收入与通胀对照：工资上涨 3%、生活成本上涨 4%，实际购买力仍可能下降。美国 7 月 PCE 价格指数同比上涨 3.7%，同月名义个人消费支出仅环比增加 0.2%，说明“物价涨幅”和“当月支出增长”不能混为一谈。",
      },
      {
        heading: "第三步：低失业率也可能与招聘疲弱并存",
        text: "失业率的分母是劳动力人口，只统计正在工作或积极找工作的人。有人停止求职并退出劳动力市场时，失业率可能下降，却不代表就业改善。因此要同时看非农就业、劳动参与率、就业人口比、工时和工资。美国 7 月非农就业减少 2.3 万人，失业率为 4.1%，劳动参与率为 61.4%；这些数据组合在一起，呈现的是招聘动能偏弱但失业率变化不大的劳动力市场，而不是一句“就业好”或“就业差”能够概括的状态。",
      },
      {
        heading: "第四步：把增长、通胀与就业放进政策反应函数",
        text: "需求强、就业紧通常会提高价格压力，需求弱则可能抑制通胀并伤害就业，但供给冲击会打破这条直觉：能源短缺可以在增长放缓时推高物价。货币政策主要通过利率、信贷和资产价格影响需求，财政政策通过税收与支出改变总需求和资源配置；两者都有时滞，也会被汇率、债务和金融稳定约束。所谓软着陆，是让通胀回落而不造成严重就业损失，不是一条可以由单个数据点确认的直线。",
      },
      {
        heading: "从数据到投资：先问冲击来自需求还是供给",
        text: "同样是增长放缓，若源于需求不足，利率下行可能同时支持债券和股票估值；若源于能源或贸易供给冲击，通胀黏性可能迫使利率保持高位，企业利润率也会受压。分析市场时可依次问四个问题：增长在加速还是减速，通胀在扩散还是收窄，就业和工资是否支持消费，政策空间是在扩大还是缩小。最后再检查价格是否已经反映预期。宏观判断影响折现率和盈利情景，却不能替代对企业现金流、估值与风险承受能力的研究。",
      },
    ],
    case_study: {
      event: "两套最新数据，为什么同时出现绿灯与黄灯",
      period: "中国 2026 年 8 月 PMI；美国 2026 年二季度与 7 月数据",
      text: "中国 8 月制造业 PMI 从上月回升 0.6 个百分点至 49.8，生产指数和新订单指数分别为 50.4 和 50.6，显示供需边际改善；但制造业 PMI 总体仍低于 50，原材料库存和从业人员指数分别为 48.1 和 48.7，非制造业商务活动指数也为 49.0。美国方面，二季度真实 GDP 按年率增长 1.5%，7 月 PCE 通胀同比为 3.7%，非农就业减少 2.3 万人而失业率维持 4.1%。两国口径不能横向拼成一个分数，但都说明相同的方法论：边际改善不等于全面扩张，增长存在也不等于通胀与就业已经回到舒适区。",
    },
    pros: {
      label: "这套宏观框架能帮助什么",
      items: [
        "把增长、价格和就业放在同一条因果链上，减少被单个标题数字带偏的概率",
        "区分经济数据的水平、增速与结构，判断改善究竟是反弹、扩张还是统计波动",
        "把政策时滞和市场预期纳入估值，理解好数据为何有时反而触发资产价格下跌",
      ],
    },
    cons: {
      label: "最常见的三种误读",
      items: [
        "把 PMI 低于 50 解读为产出绝对下降；它首先反映受访企业较上月扩张与收缩的广度",
        "把通胀回落等同于物价回到过去水平，忽略价格水平仍可能继续上升",
        "把低失业率当作充分就业的唯一证明，忽略劳动参与、招聘、工时与就业质量",
      ],
    },
    takeaways: [
      "先辨认口径：名义还是真实、同比还是环比、水平还是变化率。",
      "再看组合：增长、通胀、就业和政策空间至少要四项交叉验证。",
      "区分需求冲击与供给冲击，因为它们对利率、利润和资产价格的含义不同。",
      "宏观数据是情景输入，不是买卖指令；估值和风险边界仍要单独检查。",
    ],
  },
  markets: [
    {
      id: "cn",
      region_zh: "中国内地",
      region_en: "China Mainland",
      as_of: "2026-08-31 收盘",
      indices: [{ name: "上证指数", close: 3986.3, change_pct: 0.86 }],
      commentary: "上证指数在 8 月制造业 PMI 回升但仍略低于荣枯线的背景下收涨。市场选择交易边际改善，但订单、就业与非制造业读数提醒投资者，复苏广度仍需要后续数据确认。",
    },
    {
      id: "hk",
      region_zh: "中国香港",
      region_en: "Hong Kong",
      as_of: "2026-08-31 收盘",
      indices: [
        { name: "恒生指数", close: 25402, change_pct: -0.7 },
        { name: "恒生科技指数", close: 4557, change_pct: -1.0 },
      ],
      commentary: "港股未跟随内地主要指数上行，恒生科技指数跌幅更大。同一宏观消息在不同市场产生不同价格反应，往往来自行业权重、资金流和此前预期的差异。",
    },
    {
      id: "jp",
      region_zh: "日本",
      region_en: "Japan",
      as_of: "2026-08-31 收盘",
      indices: [{ name: "日经 225", close: 66311.93, change_pct: -0.14 }],
      commentary: "日经 225 小幅回落。日本资产仍同时受国内工资与通胀、央行政策路径、日元和全球科技周期影响，单日指数方向不足以确认宏观趋势。",
    },
    {
      id: "kr",
      region_zh: "韩国",
      region_en: "South Korea",
      as_of: "2026-08-31 收盘",
      indices: [{ name: "KOSPI", close: 6820.02, change_pct: 0.46 }],
      commentary: "KOSPI 逆转早段弱势并收涨。出口和半导体权重使韩国股市对全球需求、汇率与科技资本开支格外敏感，是观察外向型经济周期的重要窗口。",
    },
    {
      id: "us",
      region_zh: "美国",
      region_en: "United States",
      as_of: "2026-08-28 收盘",
      indices: [
        { name: "道琼斯工业指数", close: 53559.99, change_pct: -0.02, extra: "本周 +0.5%" },
        { name: "标普 500", close: 7711.76, change_pct: -0.25, extra: "本周 +0.5%" },
        { name: "纳斯达克综合指数", close: 26402.42, change_pct: -0.52, extra: "本周 +0.8%" },
      ],
      commentary: "三大指数周五回落但周线仍上涨。二季度增长放缓、7 月通胀偏高与就业动能减弱并存，令利率路径既不能只用“降息利好”解释，也不能简单归结为经济衰退交易。",
    },
    {
      id: "eu",
      region_zh: "欧洲",
      region_en: "Europe",
      as_of: "2026-08-28 收盘",
      indices: [{ name: "STOXX Europe 600", close: 655.16, change_pct: 0.51, extra: "本周约 +0.15%" }],
      commentary: "欧洲基准指数周五反弹并录得温和周涨幅。增长、财政与能源价格仍共同决定地区风险溢价；8 月 31 日欧洲交易尚未完成，因此本期不把盘中报价冒充收盘。",
    },
  ],
  movers: [
    {
      id: 1,
      kind: "宏观数据",
      kind_en: "Macro data",
      market: "中国",
      title: "制造业 PMI 回升至 49.8，生产与订单先越过 50",
      text: "8 月制造业 PMI 较上月上升 0.6 个百分点，生产和新订单指数进入扩张区间；但总体 PMI、就业和原材料库存仍低于 50。数据更接近“边际修复”，尚不足以证明各部门同步扩张。",
      source_label: "国家统计局",
      source_url: "https://www.stats.gov.cn/sj/zxfbhjd/202608/t20260831_1965154.html",
    },
    {
      id: 2,
      kind: "增长与通胀",
      kind_en: "Growth and inflation",
      market: "美国",
      title: "二季度真实 GDP 增长 1.5%，价格压力仍高于舒适区",
      text: "BEA 二次估算显示二季度真实 GDP 按年率增长 1.5%，较一季度的 2.1% 放缓；同期 PCE 价格指数按年率上涨 5.3%，而 7 月 PCE 价格指数同比上涨 3.7%。不同时间频率不能直接相减，却共同说明增长降温并未自动消除价格压力。",
      source_label: "U.S. Bureau of Economic Analysis",
      source_url: "https://www.bea.gov/news/2026/gdp-second-estimate-and-corporate-profits-2nd-quarter-2026",
    },
    {
      id: 3,
      kind: "劳动力市场",
      kind_en: "Labour market",
      market: "美国",
      title: "失业率变化不大，非农就业与参与率却提示降温",
      text: "7 月非农就业减少 2.3 万人，失业率为 4.1%，劳动参与率为 61.4%；5 月和 6 月新增就业合计还被下修 10.3 万人。失业率稳定与招聘转弱可以同时成立，劳动力市场必须用多项指标交叉判断。",
      source_label: "U.S. Bureau of Labor Statistics",
      source_url: "https://www.bls.gov/news.release/empsit.htm",
    },
    {
      id: 4,
      kind: "市场分化",
      kind_en: "Market divergence",
      market: "亚洲",
      title: "内地与韩国收涨，香港与日本回落",
      text: "上证指数和 KOSPI 分别上涨 0.86%和 0.46%，恒生指数与日经 225 分别下跌约 0.7%和 0.14%。区域内方向分化表明，宏观数据进入价格之前，还要经过行业结构、汇率与预期差的过滤。",
    },
  ],
  companies: [],
  sources: [
    {
      label: "国际货币基金组织",
      title: "Measures of Output, Employment, and the Price Level",
      url: "https://www.elibrary.imf.org/display/book/9781557758750/ch004.xml",
      published: "2000",
    },
    {
      label: "国家统计局",
      title: "2026年8月中国采购经理指数运行情况",
      url: "https://www.stats.gov.cn/sj/zxfbhjd/202608/t20260831_1965154.html",
      published: "2026-08-31",
    },
    {
      label: "国家统计局",
      title: "8月份制造业采购经理指数明显回升",
      url: "https://www.stats.gov.cn/sj/sjjd/202608/t20260831_1965155.html",
      published: "2026-08-31",
    },
    {
      label: "U.S. Bureau of Economic Analysis",
      title: "GDP (Second Estimate) and Corporate Profits, 2nd Quarter 2026",
      url: "https://www.bea.gov/news/2026/gdp-second-estimate-and-corporate-profits-2nd-quarter-2026",
      published: "2026-08-26",
    },
    {
      label: "U.S. Bureau of Economic Analysis",
      title: "Personal Income and Outlays, July 2026",
      url: "https://www.bea.gov/data/income-saving/personal-income",
      published: "2026-08-26",
    },
    {
      label: "U.S. Bureau of Economic Analysis",
      title: "Personal Consumption Expenditures Price Index",
      url: "https://www.bea.gov/data/personal-consumption-expenditures-price-index",
      published: "2026-08-26",
    },
    {
      label: "U.S. Bureau of Labor Statistics",
      title: "The Employment Situation — July 2026",
      url: "https://www.bls.gov/news.release/empsit.htm",
      published: "2026-08-07",
    },
    {
      label: "Minkabu FX",
      title: "上海综合指数は0.86%高の3986.30で取引終了",
      url: "https://fx.minkabu.jp/news/377588",
      published: "2026-08-31",
    },
    {
      label: "ET Net News Agency",
      title: "HSI ends down 182 pts at 25,402; HSTECH down 47 pts at 4,557",
      url: "https://www.etnet.com.hk/www/eng/futures/futures_news_detail.php?newsid=20260831190",
      published: "2026-08-31",
    },
    {
      label: "Kabutan",
      title: "日経平均大引け：前週末比93.63円安の66311.93円",
      url: "https://s.kabutan.jp/news/n202608310706/",
      published: "2026-08-31",
    },
    {
      label: "Maeil Business Newspaper",
      title: "KOSPI closes at 6,820.02, up 0.46%",
      url: "https://www.mk.co.kr/news/stock/12140429",
      published: "2026-08-31",
    },
    {
      label: "Associated Press",
      title: "How major US stock indexes fared Friday 8/28/2026",
      url: "https://apnews.com/article/3f3477bcea915ac53ec2ae905ae57919",
      published: "2026-08-28",
    },
    {
      label: "Reuters / Yahoo Finance",
      title: "European shares rise as French stocks rebound; markets digest Warsh speech",
      url: "https://finance.yahoo.com/markets/world-indices/articles/european-shares-rise-french-stocks-162928091.html",
      published: "2026-08-28",
    },
  ],
};
