import type { DailyReport } from "../report-types";

export const realReport20260825: DailyReport = {
  id: "2026-08-25",
  date: "2026-08-25",
  published_at: "2026-08-25T08:30:00+08:00",
  updated_at: "2026-08-25T08:30:00+08:00",
  edition_number: 5,
  draft: false,
  estimated_minutes: 38,
  ai_credit: { provider: "OpenAI", model: "GPT-5.6 Luna", role: "资料研究、事实核查与编辑协作" },
  sources: [
    { label: "新浪财经", title: "阿里拟配售募资约800亿港元，全部用于投资全栈AI能力", url: "https://finance.sina.com.cn/stock/s/2026-08-25/doc-inipnpze2451102.shtml", published: "2026-08-25" },
    { label: "新浪财经", title: "中美1.5轨对话在北京举行，将探索人工智能与科技合作", url: "https://finance.sina.com.cn/7x24/2026-08-25/doc-inipnuhw1624209.shtml", published: "2026-08-25" },
    { label: "Reuters / Investing", title: "Dollar struggles as markets weigh Iran sanctions and Treasury buybacks", url: "https://www.investing.com/news/economy-news/dollar-struggles-as-markets-weigh-iran-sanctions-treasury-buybacks-4874390", published: "2026-08-25" },
    { label: "Reuters / Metrobank", title: "Global markets: tech pressure, lower yields and oil", url: "https://wealthinsights.metrobank.com.ph/news/global-markets-shares-dip-with-pressure-from-technology-yields-and-oil-fall", published: "2026-08-25" },
    { label: "财联社 / 东方财富", title: "8月25日早间新闻精选：央行开展5000亿元MLF操作", url: "https://finance.eastmoney.com/a/202608253851927294.html", published: "2026-08-25" },
  ],
  big_story: {
    category: "AI · Technology · Markets",
    title_zh: "800 亿港元押注 AI：阿里把基础设施账单交给资本市场",
    title_en: "Alibaba puts an HK$80 billion AI bet before the market",
    summary: "阿里巴巴 8 月 24 日宣布拟按每股 112.70 港元配售 7.1 亿股新股，预计募资约 800 亿港元，净额将全部投入全栈 AI 能力与基础设施。消息公布后，阿里港股一度大跌；董事会主席蔡崇信与 CEO 吴泳铭随后合计增持约 1.2 亿港元股票。这个动作同时提出两个问题：大型平台是否必须继续为算力、模型和数据中心付出重资本，以及投资者愿意等多久才看到回报。",
    minutes: 12,
    source_label: "新浪财经",
    source_url: "https://finance.sina.com.cn/stock/s/2026-08-25/doc-inipnpze2451102.shtml",
  },
  hot_words: [
    { en: "Private placement", zh: "配售；定向增发", ja: "株式の割当（かぶしきのわりあて）", ja_romaji: "kabushiki no wariate", ko: "주식 배정", ko_romaja: "jusik baejeong", why_today: "阿里拟通过配售新股筹资约 800 亿港元，配售是今天理解这笔融资的第一把钥匙。", example: "Alibaba plans a private placement to fund its AI expansion.", topic: "Markets" },
    { en: "AI infrastructure", zh: "AI 基础设施", ja: "AIインフラ", ja_romaji: "AI infura", ko: "AI 인프라", ko_romaja: "AI inpeura", why_today: "资金用途被明确指向算力、数据中心和全栈能力，而不是一次性的产品发布。", example: "AI infrastructure requires years of capital spending.", topic: "Technology" },
    { en: "Capital expenditure", zh: "资本性支出", ja: "設備投資（せつびとうし）", ja_romaji: "setsubi tōshi", ko: "자본적 지출", ko_romaja: "jabonjeok jichul", why_today: "AI 竞争正在从模型参数竞争转为长期设备投资竞争。", example: "Capital expenditure is rising as firms build data centers.", topic: "Finance" },
    { en: "Return on investment", zh: "投资回报", ja: "投資収益率（とうししゅうえきりつ）", ja_romaji: "tōshi shūekiritsu", ko: "투자수익률", ko_romaja: "tujasuyungnyul", why_today: "市场真正要问的不是投入规模，而是投入何时转化为收入、利润与用户黏性。", example: "Investors are asking when the AI spending will earn a return.", topic: "Markets" },
    { en: "Dilution", zh: "股权稀释", ja: "株式の希薄化（かぶしきのきはくか）", ja_romaji: "kabushiki no kihakuka", ko: "지분 희석", ko_romaja: "jibun huisok", why_today: "增发会扩大股本，原有股东的持股比例可能被摊薄，因此融资与回报必须同时衡量。", example: "A new share issue may dilute existing shareholders.", topic: "Finance" },
    { en: "Secondary sanctions", zh: "次级制裁", ja: "二次制裁（にじせいさい）", ja_romaji: "niji seisai", ko: "2차 제재", ko_romaja: "icha jejae", why_today: "美国扩大对与伊朗保持商业关系实体的制裁，美元资产与跨境贸易承受新的政策不确定性。", example: "Secondary sanctions can affect firms that do not trade directly with Iran.", topic: "Policy" },
    { en: "Treasury buybacks", zh: "美债回购", ja: "国債買い戻し（こくさいかいもどし）", ja_romaji: "kokusai kaimodoshi", ko: "국채 바이백", ko_romaja: "gukchae baibaek", why_today: "美国财政部的长期国债回购计划成为市场观察利率与流动性的一个新变量。", example: "Treasury buybacks may ease pressure in longer-dated bonds.", topic: "Markets" },
    { en: "Trade retaliation", zh: "贸易反制", ja: "貿易報復（ぼうえきほうふく）", ja_romaji: "bōeki hōfuku", ko: "무역 보복", ko_romaja: "muyeok bobok", why_today: "美加谈判破裂后，关税与反制措施继续影响加元、商品价格和供应链预期。", example: "Trade retaliation can spread beyond the original sector.", topic: "Trade" },
    { en: "1.5-track dialogue", zh: "1.5 轨对话", ja: "一・五トラック対話", ja_romaji: "ichi-ten-go torakku taiwa", ko: "1.5 트랙 대화", ko_romaja: "iljeom-o teuraek daehwa", why_today: "中美代表在北京讨论政治互信、经贸合作和 AI 科技合作，处于官方与民间之间的沟通层。", example: "The 1.5-track dialogue explores practical areas for cooperation.", topic: "Diplomacy" },
  ],
  expressions: [
    { language: "English", flag: "EN", phrase: "put money where your mouth is", romanization: "", meaning: "用真金白银兑现立场", nuance: "用于形容一个人或公司不只发表观点，还拿出实际资金支持自己的判断。", scene: "公司战略、市场评论", dialogue: "A: Does management really believe in its AI strategy?\nB: It is putting money where its mouth is.", register: "中性 · 评论语境", frequency: "常用", note: "语气略带评论性，也可用于个人承诺。" },
    { language: "日本語", flag: "JP", phrase: "背水の陣を敷く。", romanization: "haisui no jin o shiku", meaning: "背水一战；下定决心投入到底。", nuance: "原指背靠河水布阵，现用于形容没有退路、必须集中力量完成目标。", scene: "商业报道、人物评论", dialogue: "A：これほど大きな投資は危険ではありませんか。\nB：AI事業に背水の陣を敷いたのでしょう。", register: "稍书面 · 自然", frequency: "常用", note: "比喻色彩明显，适合标题与评论。" },
    { language: "한국어", flag: "KR", phrase: "승부수를 던지다.", romanization: "seungbusureul deonjida", meaning: "打出决定胜负的一招。", nuance: "常用于企业推出重大投资、产品或战略，强调风险与决断并存。", scene: "商业新闻、战略讨论", dialogue: "A: 이번 증자는 어떤 의미인가요?\nB: AI 인프라에 승부수를 던진 셈입니다.", register: "中性 · 新闻语境", frequency: "常用", note: "字面是“投出胜负手”，可用于棋局或商业。" },
  ],
  briefings: [
    { id: 1, category: "AI / Markets", title_zh: "阿里拟募资 800 亿港元，全部投向 AI", title_en: "Alibaba plans an HK$80 billion AI fundraise", source: "新浪财经", source_url: "https://finance.sina.com.cn/stock/s/2026-08-25/doc-inipnpze2451102.shtml", minutes: 3, zh: "阿里巴巴宣布拟配售 7.1 亿股新股，每股 112.70 港元，预计募资约 800 亿港元，净额全部用于全栈 AI 能力和基础设施。公司管理层随后增持股票，试图向市场传达长期投入的信心。", en: "Alibaba said it plans to place 710 million new shares at HK$112.70 each, raising about HK$80 billion. The net proceeds will go entirely to full-stack AI capabilities and infrastructure. Its top executives then bought shares, signalling confidence in the long-term plan.", ja: "アリババは七億一千万株の新株を一株百十二・七香港ドルで割り当て、約八百億香港ドルを調達する計画を発表しました。資金はすべてAI能力とインフラに使われます。", ko: "알리바바는 신주 7억 1000만 주를 주당 112.70홍콩달러에 배정해 약 800억 홍콩달러를 조달할 계획이라고 밝혔습니다. 자금은 모두 AI 역량과 인프라에 사용됩니다.", ja_segments: [{ text: "アリババ", romanization: "aribaba", zh: "阿里巴巴" }, { text: "は", romanization: "wa", zh: "主题" }, { text: "新株", reading: "しんかぶ", romanization: "shinkabu", zh: "新股" }, { text: "を", romanization: "o", zh: "宾语" }, { text: "割り当てます。", reading: "わりあてます", romanization: "wariatemasu", zh: "进行配售。" }], ko_segments: [{ text: "알리바바는", romanization: "allibaba-neun", zh: "阿里巴巴（主题）" }, { text: "신주를", romanization: "sinjureul", zh: "新股（宾语）" }, { text: "배정합니다.", romanization: "baejeonghamnida", zh: "进行配售。" }] },
    { id: 2, category: "Diplomacy / AI", title_zh: "中美 1.5 轨对话：讨论 AI 与科技合作", title_en: "China-US 1.5-track dialogue discusses AI cooperation", source: "新浪财经", source_url: "https://finance.sina.com.cn/7x24/2026-08-25/doc-inipnuhw1624209.shtml", minutes: 3, zh: "第三届中美 1.5 轨对话 8 月 25 日在北京举行，议题包括增进政治互信、拓展经贸合作，以及探索人工智能与科技合作。它不是正式外交谈判，却为政策、产业和学术界提供了较灵活的沟通场域。", en: "The third China-US 1.5-track dialogue took place in Beijing on August 25. Participants discussed political trust, economic cooperation and possible work on AI and technology. It is not formal diplomacy, but it creates a more flexible channel among policy, business and academic actors.", ja: "第三回中米一・五トラック対話が八月二十五日に北京で開かれ、政治的信頼や経済協力、AIと科学技術の協力が議論されました。", ko: "제3차 미중 1.5트랙 대화가 8월 25일 베이징에서 열렸습니다. 정치적 신뢰, 경제 협력, AI와 과학기술 협력이 논의됐습니다.", ja_segments: [{ text: "対話", reading: "たいわ", romanization: "taiwa", zh: "对话" }, { text: "が", romanization: "ga", zh: "主语" }, { text: "北京", reading: "ペキン", romanization: "Pekin", zh: "北京" }, { text: "で", romanization: "de", zh: "在" }, { text: "開かれました。", reading: "ひらかれました", romanization: "hirakaremashita", zh: "举行了。" }], ko_segments: [{ text: "대화가", romanization: "daehwaga", zh: "对话（主语）" }, { text: "베이징에서", romanization: "beijing-eseo", zh: "在北京" }, { text: "열렸습니다.", romanization: "yeollyeotseumnida", zh: "举行了。" }] },
    { id: 3, category: "Markets / Policy", title_zh: "美元承压：制裁、回购与美债收益率成为变量", title_en: "The dollar faces sanctions, buybacks and bond-market nerves", source: "Reuters / Investing", source_url: "https://www.investing.com/news/economy-news/dollar-struggles-as-markets-weigh-iran-sanctions-treasury-buybacks-4874390", minutes: 3, zh: "路透社报道，市场正在消化美国扩大对伊朗相关实体的制裁，以及美国财政部回购长期国债的安排。美元难以维持涨幅，投资者也在等待美联储主席 Kevin Warsh 在杰克逊霍尔的讲话。", en: "Reuters reported that markets were weighing expanded US sanctions on Iran-linked entities and Treasury efforts to buy back longer-dated bonds. The dollar struggled to hold gains while investors awaited Fed Chair Kevin Warsh's speech at Jackson Hole.", ja: "市場はイラン関連の制裁拡大と、米財務省による長期国債の買い戻しを見極めています。ドルは上昇を維持しにくくなっています。", ko: "시장은 이란 관련 제재 확대와 미국 재무부의 장기 국채 바이백을 지켜보고 있습니다. 달러는 상승폭을 유지하기 어려운 모습입니다.", ja_segments: [{ text: "市場", reading: "しじょう", romanization: "shijō", zh: "市场" }, { text: "は", romanization: "wa", zh: "主题" }, { text: "ドル", romanization: "doru", zh: "美元" }, { text: "を", romanization: "o", zh: "宾语" }, { text: "見極めています。", reading: "みきわめています", romanization: "mikiwameteimasu", zh: "正在判断。" }], ko_segments: [{ text: "시장은", romanization: "sijang-eun", zh: "市场（主题）" }, { text: "달러를", romanization: "dalleoreul", zh: "美元（宾语）" }, { text: "지켜봅니다.", romanization: "jikyeobomnida", zh: "观察。" }] },
    { id: 4, category: "China / Monetary Policy", title_zh: "央行开展 5000 亿元 MLF 操作", title_en: "China's central bank conducts a 500 billion yuan MLF operation", source: "财联社 / 东方财富", source_url: "https://finance.eastmoney.com/a/202608253851927294.html", minutes: 3, zh: "8 月 25 日，央行开展 5000 亿元中期借贷便利（MLF）操作，期限为一年。市场同时关注 8 月 27 日至 9 月 1 日的隔夜逆回购安排，流动性节奏仍是观察国内资产价格的重要线索。", en: "On August 25, China's central bank conducted a 500 billion yuan, one-year medium-term lending facility operation. Markets are also watching the planned overnight reverse repos from August 27 to September 1 as a signal for liquidity conditions.", ja: "八月二十五日、中国人民銀行は五千億元の一年物中期貸出ファシリティを実施しました。市場は今後の流動性の動きにも注目しています。", ko: "8월 25일 중국 인민은행은 5000억 위안 규모의 1년 만기 중기대출제도 조작을 실시했습니다. 시장은 앞으로의 유동성 흐름도 주목하고 있습니다.", ja_segments: [{ text: "中国人民銀行", reading: "ちゅうごくじんみんぎんこう", romanization: "Chūgoku Jinmin Ginkō", zh: "中国人民银行" }, { text: "は", romanization: "wa", zh: "主题" }, { text: "五千億元", reading: "ごせんおくげん", romanization: "gosen oku gen", zh: "5000 亿元" }, { text: "を", romanization: "o", zh: "宾语" }, { text: "実施しました。", reading: "じっししました", romanization: "jisshi shimashita", zh: "实施了。" }], ko_segments: [{ text: "중국인민은행은", romanization: "jungguginmin-eunhaeng-eun", zh: "中国人民银行（主题）" }, { text: "5000억", romanization: "ocheon-eok", zh: "5000 亿元" }, { text: "위안을", romanization: "wian-eul", zh: "元（宾语）" }, { text: "실시했습니다.", romanization: "silsilhaetseumnida", zh: "实施了。" }] },
  ],
  deep_read: {
    category: "AI · Markets · Corporate Strategy",
    title_en: "The AI bill arrives before the AI dividend",
    title_zh: "AI 红利尚未兑现，基础设施账单已经到来",
    minutes: 13,
    standfirst: "阿里这次融资的意义，不在于 800 亿港元本身，而在于它把 AI 竞争的成本结构摊在了投资者面前：模型要算力，算力要数据中心，数据中心需要连续多年资本开支。市场过去愿意为 AI 的想象力付费，现在开始追问这条投入链最终如何回到利润表。",
    paragraphs: [
      { en: "The capital raise turns an abstract AI strategy into a measurable financial commitment. Alibaba says the proceeds will be used entirely for full-stack AI capability and infrastructure. That wording matters: the company is not presenting AI as a feature added to an existing business, but as a new layer that reaches from chips and compute to models, applications and distribution.", zh: "这次融资把抽象的 AI 战略变成了一项可以计量的财务承诺。阿里明确表示，募资净额将全部用于全栈 AI 能力和基础设施。这个表述很重要：公司并不是把 AI 当成既有业务上的一个功能，而是在建设一层从芯片、算力到模型、应用和分发的完整系统。" },
      { en: "Infrastructure spending has a different rhythm from software revenue. A data center is paid for before it is fully utilized; accelerators depreciate while demand is still being built; electricity, networking and cooling become recurring costs. This creates a timing gap between cash leaving the company and AI revenue arriving in the accounts.", zh: "基础设施投入与软件收入的节奏不同。数据中心要在充分利用之前先付钱，AI 加速器在需求形成的同时就开始折旧，电力、网络和散热还会变成持续成本。这会制造一个时间差：现金先离开公司，AI 收入却要晚一些才进入账目。" },
      { en: "That timing gap is why the market reacted to the placement rather than simply applauding it. New shares can dilute existing ownership, while the promised return remains uncertain. Management buying shares may signal conviction, but it does not remove execution risk. The question is whether Alibaba can convert infrastructure scale into lower unit costs, better products and durable customer demand.", zh: "正因为有这个时间差，市场面对配售时没有只做鼓掌动作。新股会稀释原有持股比例，而承诺中的回报仍然不确定。管理层增持可以表达信心，却不能消除执行风险。真正的问题是：阿里能否把基础设施规模转化成更低的单位成本、更好的产品和更持久的客户需求。" },
      { en: "The wider market is making the same calculation. Reuters noted that technology weakness was weighing on global equities while investors awaited Nvidia's results and watched bond yields, tariffs and sanctions. AI is no longer a single-sector story: its cost of capital is linked to rates, its supply chain to trade policy, and its revenue promise to the willingness of ordinary businesses to pay.", zh: "更广泛的市场也在做同一道计算题。路透社指出，科技股走弱拖累全球股市，投资者同时等待英伟达业绩，并观察美债收益率、关税和制裁。AI 已经不再是单一行业故事：它的资本成本与利率相连，供应链与贸易政策相连，收入承诺则取决于普通企业是否愿意持续付费。" },
      { en: "A useful way to read today's announcement is not as a verdict on Alibaba, but as a test for the entire AI economy. The next signal will be less dramatic than a fundraise: utilization rates, recurring revenue, inference costs and customer retention. Those are the numbers that will decide whether today's infrastructure is tomorrow's advantage or simply tomorrow's depreciation.", zh: "理解今天这笔融资，不必急着把它当成对阿里的判决，更可以把它看作对整个 AI 经济的测试。下一步值得看的信号不会像融资新闻这样戏剧化，而是利用率、经常性收入、推理成本和客户留存。这些数字最终决定，今天的基础设施究竟会成为明天的优势，还是只会变成明天的折旧。" },
    ],
  },
  context: [
    { title: "为什么 AI 基础设施这么烧钱？", text: "训练和运行模型都需要大量 GPU、网络设备、存储、电力与散热。训练是一次性高峰，推理则随着用户增长持续发生；企业必须同时承担建设成本和运行成本。" },
    { title: "配售和普通借款有什么不同？", text: "配售通过发行新股获得资金，不需要像借款一样固定偿还本金和利息，但会扩大股本并稀释原有股东比例。它把未来增长的一部分风险和收益交给新股投资者共同承担。" },
    { title: "什么是 1.5 轨对话？", text: "它介于政府正式外交与纯民间交流之间，参与者可以包括政府部门、智库、企业和学者。它不能替代正式谈判，但能为具体合作议题保留沟通空间。" },
  ],
  history_lens: null,
  challenge: [
    { id: 1, kind: "English", question: "What does 'put money where your mouth is' mean in today's issue?", options: ["用资金兑现公开立场", "把钱放在嘴边", "减少资本性支出"], answer: 0, explanation: "The phrase means to support what you say with real action or money." },
    { id: 2, kind: "日本語", question: "「背水の陣を敷く」最接近的中文意思是？", options: ["背水一战", "控制风险", "暂缓投资"], answer: 0, explanation: "背水の陣を敷く means to commit to a decisive, no-retreat effort." },
    { id: 3, kind: "한국어", question: "“승부수를 던지다”是什么意思？", options: ["打出决定胜负的一招", "降低价格", "退出市场"], answer: 0, explanation: "승부수 means a decisive move intended to determine the result." },
    { id: 4, kind: "Translation", question: "“AI 红利尚未兑现，基础设施账单已经到来。”最自然的英文是？", options: ["The AI dividend has yet to arrive, but the infrastructure bill is already here.", "AI profit does not come, infrastructure pays.", "The AI bill is a dividend."], answer: 0, explanation: "The first option preserves both the timing contrast and the financial metaphor." },
    { id: 5, kind: "Knowledge", question: "配售新股最直接的结构性影响是什么？", options: ["扩大股本并可能稀释原有股东比例", "保证公司利润立刻增长", "自动降低利率"], answer: 0, explanation: "A share placement raises equity capital but increases the number of shares outstanding." },
  ],
  completion: false,
  difficulty_feedback: null,
};
